INSERT INTO questions (question, answer_1, answer_2, answer_3, answer_4, bible, answer, difficulty) VALUES 
('Wann feiern wir den Geburtstag von Jesus?','Heiligabend','1.Weihnachtstag','2.Weihnachtstag','4.Advent','Die Bibel  nennt uns nicht den genauen Geburtstag von Jesus.',1,1),
('Wer war Jesus','Gottes Sohn','Musiker','Politiker','Sportler','Lies z.B. Johannes 3 Vers 16; oder 1. Johannesbrief 4 Vers 9',1,1),
('Wie viele Jünger hatte Jesus','7','10','12','40','Lies z.B. Matthäus 10 Vers 1',3,1),
('Wie hießen die Eltern von Jesus?','Zacharias und Elisabeth','Adam und Eva','Johannes und Maria','Josef und Maria','Lies z.B. Lukas 2 Vers 16',4,1),
('Wer führte das Volk Israel aus Ägypten?','David','Jakob','Esau','Mose','Lies z.B. 2. Mose 3 Vers 10',4,1),
('Wen bewahrte Gott vor den Löwen?','Daniel','Jona','Bileam','Paulus','Lies Daniel 6 Vers 22 und 23',1,1),
('Wie starb Jesus','Steinigung','Natürlicher Tod','Kreuzigung','Unbekannt','Lies z.B. Matthäus 27 Vers 35 ff',3,1),
('Wo wurde Jesus gekreuzigt?','Berg Golgatha','Tempelberg','Berg Karmel','Berg Sinai','Lies z.B. Matthäus 27 Vers 33',1,1),
('Wie hoch war der Turm zu Babel?','85 m','135 m','150m','Unbekannt','Lies 1. Mose 11. Die einzige Höhenangabe dort lautet: "dessen Spitze bis an den Himmel reiche"',4,1),
('Wie verhinderte Gott die Vollendung des Turmbaus in Babel?','Erdbeben','Krankheit','Sprachenentstehung','Unbekannt','Lies 1. Mose 11 Vers 7 und 8',3,1),
('Wann feiern wir die Auferstehung von Jesus','Ostern','Pfingsten','Himmelfahrt','Karfreitag','Der Name "Ostern" für den Tag der Auferstehung Jesu, findet sich in der Bibel selbst nicht.',1,1),
('Was verkündete der Engel den Hirten bei der Geburt Jesu?','Gottes Strafe','Große Freude','Viele Nachkommen','Gar nichts','Lies Lukas 2 Vers 10',2,1),
('Was aßen die Israeliten in der Wüste?','Kokosnüsse','Manner','Manna','Brot','Lies 2. Mose 16 Vers 31',3,1),
('Was ist keins der 10 Gebote?','Nicht stehlen','Keine anderen Götter haben','Nicht töten','Nicht die Umwelt verschmutzen','Vergleiche 2. Mose 20 Vers 1-17',4,1),
('Wer besiegte Goliat?','Daniel','Darius','David','Dagobert','Lies 1. Samuel 17 Vers 1 bis 58',3,1),
('Was ist keine der 10 Plagen?','Finsternis','Heuschrecken','Stechfliegen','Kopfschmerzen','Vergleiche 2. Mose 7 Vers 14 bis 12 Vers 29',4,1),
('Wer ist der älteste Mensch der Bibel?','Noah','Abraham','Methusalem','Unbekannt','Lies 1. Mose 5 Vers 25 bis 27',3,1),
('In welche zwei Teile ist die Bibel unterteilt?','1.       Und 2. Kapitel','Altes und Neues Testament','Vorwort und Hauptteil','Berichte und Gedichte','Siehe im Inhaltsverzeichnis einer Bibel',2,1),
('Wovon handelt Psalm 23?','Vom Beten','Von Gott als Hirte','Von Sündenvergebung','Von Gott als dem Richter','Lies Psalm 23 Vers 1',2,1),
('In welchem Kindesalter redete Jesus mit den Schriftgelehrten? ','Mit 12 Jahren','Mit 14 Jahren','Mit 17 Jahren','unbekannt','Lies Lukas 2 Vers 41 bis 51',1,1),
('Wann erschuf Gott den Menschen?','Am ersten Tag','Am dritten Tag','Am sechsten Tag','Am siebten Tag','Lies 1. Mose 1 Vers 24 bis 31',3,1),
('Was sind die ersten Worte der Bibel?','Es war einmal…','Am Anfang schuf Gott Himmel und Erde.','Aufgepasst, was jetzt kommt ist äußerst wichtig!','Liebe Leserin, lieber Leser …','Lies 1. Mose 1 Vers 1',2,1),
('Von welcher Frucht aßen Eva und Adam verbotener Weise?','Apfel','Orange','Mango','Unbekannt','Vergleiche 1. Mose 3 Vers 1 bis 7',4,1),
('Wie zog Jesus nach Jerusalem ein?','Er ritt auf einem Esel','Er wurde in einer Sänfte getragen','Er wanderte durch die Straßen','Als Sohn Gottes schwebte er hinein','Lies z.B. Matthäus 21 Vers 1 bis 11',1,1),
('Was machten die Jünger als Jesus im Garten Gethsemane betete?','Karten spielen','Wache halten','Schlafen','Mit beten','Lies z.B. Matthäus 26 Vers 40',3,1),
('Was bewirkte der Heilige Geist beim ersten Pfingstfest?','Die Jünger bekamen starke Muskeln','Die Jünger konnten Menschen heilen','Die Jünger dichteten neue Lieder','Die Jünger sprachen in fremden Sprachen','Lies z.B. Apostelgeschichte 2 Vers 4',4,1),
('Wer war der Bruder von Mose?','Anton','Aaron','Alfons','Ahab','Lies z.B. 2. Mose 4 Vers 14',2,1),
('Wie viele Menschen durften mit auf die Arche','2','4','6','8','Lies 1. Mose 7 Vers 13',4,1),
('Als Jesus am Kreuz starb, rief er …','Ihr seid alle schuldig','Es ist vollbracht','Ich habe Angst','Ich kann nicht mehr','Lies Johannes 19 Vers 30',2,1),
('Was machten Silas und Paulus um Mitternacht im Gefängnis','Sie lobten Gott','Sie randalierten','Sie planten einen Fluchtversuch','Sie riefen laut um Hilfe','Lies Apostelgeschichte 16 Vers 25',1,1),
('Wer verleugnete dreimal Jesus zu kennen?','Johannes','Jakobus','Petrus','Andreas','Lies z.B. Matthäus 26 Vers 69 bis 75',3,1),
('Elia wurde am Bach Krit …','Von Freunden versorgt','Durch die Jagd versorgt','Von Raben versorgt','Mit Manna versorgt','Lies 1. Könige 17 Vers 5 und 6',3,1),
('Wie besiegte David den riesen Goliat?','Mit seinem Hirtenstab','Mit seiner Steinschleuder','Durch eine Falle','Durch einen Hinterhalt','Lies 1. Samuel 17 Vers 50 und 51',2,1),
('Wer verlor seine Kraft durch das Schneiden der Haare?','Samuel','Simson','Saul','Absalom','Lies Richter 16 Vers 19',2,1),
('Was war der Lieblingssohn von Jakob','Ruben','Juda','Josef','Gad','Lies 1. Mose 37 Vers 3',3,1),
('Wie viele Söhne hatte Jakob?','6','8','10','12','Lies 1. Mose 35 Vers 22b',4,1),
('Was sollte Abraham mit seinem Sohn Isaak machen?','Er sollte ihm Schafehüten beibringen','Er sollte ihm beibringen Kriege zu führen','Er sollte ihn nie alleine im Zelt lassen','Er sollte ihn opfern','Lies 1. Mose 22 Vers 1 und 2',4,1),
('Wer baute die Stadtmauer von Jerusalem wieder auf?','Jeremia','Nehemia','Serubbabel','Niemand','Lies z.B. Nehemia 4, 1',2,1),
('Wie viele Kundschafter begutachteten das verheißene Land?','6','12','25','40','Lies 4. Mose 13 Vers 25',2,1),
('Wie hießen die 3 Geschwister mit denen Jesus befreundet war?','Lazarus, Maria, Martha','Lamech, Lea, Rahel','Eli, Elisabeth, Hannah','Lukas, Lydia, Phoebe','Lies Johannes 11 Vers 1 und 5',1,1),
('Wie starb Abel?','Er erlitt einen Herzinfarkt','Er wurde von seinem Bruder erschlagen','Er ertrank im Jordan','Er starb im Krieg','Lies 1. Mose 4 Vers 8',2,1),
('Wer war die Mutter von Kain?','Rebekka','Maria','Eva','Unbekannt','Lies 1. Mose 4 Vers 1',3,1),
('Welcher König baute den Tempel?','Saul','David','Salomo','Hiskia','Lies 1. Könige 6 Vers 1',3,1),
('Wer war Machthaber in Jerusalem als Jesus verurteilt wurde?','Julius Cäsar','Pontius Pilatus','Pontius Felix','Pontius Augustus','Lies z.B. Matthäus 27 Vers 11',2,1),
('Wer trug für Jesus das Kreuz?','Simon von Kyrene','Nikodemus','Gamaliel','Petrus','Lies z.B. Matthäus 27 Vers 32',1,1),
('Jesus hatte Petrus vorhergesagt, dass er ihn dreimal verleugnet bevor …','… die Sonne aufgeht','… die Bauern auf ihre Felder gehen','… bevor die Glocken läuten','… bevor der Hahn kräht','Lies z.B. Matthäus 26 Vers 34',4,1),
('Wer half in einem Gleichnis Jesu einem überfallenem Schwerverletzten?','Ein Priester','Ein Tempeldiener','Ein reicher Kaufmann','Ein Samariter','Lies Lukas 10 Vers 30 und 33 bis 34',4,1),
('Wie verriet Judas Iskariot Jesus?','Durch einen Kuss','Durch eine Umarmung','Durch das Händeschütteln','Durch Schulterklopfen','Lies z.B. Markus 14 Vers 44 und 45',1,1),
('Von wem wurde Jesus getauft?','Von Petrus','Von Gott selbst','Von Johannes dem Täufer','Jesus wurde nie getauft','Lies z.B. Markus 1 Vers 9',3,1),
('Wer erfuhr als erstes von der Auferstehung Jesu?','Die engsten Jünger Jesu','Die Frauen am Grab','Die Emmausjünger','Alle Jünger gleichzeitig','Lies z.B. Markus 16 Vers 1 bis 7',2,1),
('Wer konnte anfangs nicht glauben, dass Jesus auferstanden sei?','Johannes','Jakobus','Pontius Pilatus','Thomas','Lies Johannes 20 Vers 25',4,1),
('Welchen Beruf hatte Nehemia?','Oberbefehlshaber der königlichen Leibwache','Zimmermann','Priester','Mundschenk des Königs','Lies Nehemia 1 Vers 11',4,1),
('Wer kletterte auf einen Baum um Jesus zu sehen?','Zacharias','Zachäus','Zedekia','Melchisedek','Lies Lukas 19 Vers 3 und 4',2,1),
('Was tat Pontius Pilatus nachdem er Jesus verurteilt hatte?','Er kämmte seine Haare','Er winkte den jubelnden Menschen zu','Er wusch sich die Hände','Er schnäuzte sich die Nase','Lies Matthäus 27 Vers 24',3,1),
('Was tat Jesus am Abend vor seiner Kreuzigung?','Er trank zu viel Wein','Er tanzte mit seinen Freunden','Er wusch seinen Jüngern die Füße','Er verteilte seinen Besitz unter seine Jünger','Lies Johannes 13 Vers 1 und 5',3,1),
('Was wird in einem Gleichnis neunundneunzigfach zurückgelassen?','Frauen und Kinder','Gold','Freunde','Schafe','Lies z.B. Lukas 15 Vers 3 und 4',4,1),
('Wo wächst Jesus auf?','Jerusalem','Bethlehem','Nazareth','Unbekannt','Lies Lukas 2 Vers 51',3,1),
('Wer war Jakobs Lieblingsfrau?','Lea','Rahel','Rebekka','Bila','Lies 1. Mose 29 Vers 30',2,1),
('Wie heißt ein ganz bekanntest Gleichnis von Jesus?','Der verlorene Sohn','Der verrückte Sohn','Der tote Sohn','Der egoistische Sohn','Lies Lukas 15 Vers 24 und die Überschrift ab Vers 11',1,1),
('Jesus machte aus Fischern …','… Theologen','… Menschenfischer','… Adelige','… Soldaten','Lies z.B. Markus 1 Vers 17',2,1),
('Welches Versprechen gibt Gott mit dem Regenbogen? Nie mehr…','... eine weltweite Sintflut.','… eine Hungersnot.','… Streit und Hass.','… Kälte und Schnee.','Lies 1. Mose 9 Vers 12 bis 15',1,1),
('Das erste Buch des Neuen Testaments ist …','Apostelgeschichte','Römerbrief','Mätthäusevangelium','Johannesevangelium','Vergleiche im Inhaltsverzeichnis deiner Bibel.',3,1),
('Wofür ist Hiob bekannt?','Er musste viel Leid erleben.','Er ist der älteste Mensch der Bibel.','Er kämpfte mit einem Engel.','Er war der erste Jünger Jesu.','Lies Hiob Kapitel 1 und 2.',1,1),
('Was soll Esther am Hof des Königs nicht sagen?','Dass ihr die Stadt nicht gefällt','Dass ihr Pflegevater Mordechai ist','Ihre Hobbies','Dass sie Jüdin ist','Lies Esther 2 Vers 10',4,1),
('Das letzte Buch der Bibel ist …','die Offenbarung','der Hebräerbrief','Maleachi','der Judasbrief','Vergleiche im Inhaltsverzeichnis deiner Bibel. ',1,1),
('Wer noch ging außer Jesus- wenn auch nur kurz - auf dem Wasser?','Mose','Elia','Johannes der Täufer','Petrus','Lies Matthäus 14 Vers 29',4,1),
('Wer an Jesus glaubt … ','… hat keine Probleme. ','… wird nie krank. ','… bekommt alles was er sich wünscht. ','bekommt das ewige Leben.','Lies z.B. Johannes 3 Vers 16 .',4,1),
('Die Bibel bezeichnet Gott auch als … ','… die Liebe. ','… die Ungeduld.','… die Rache.','… die Willkür. ','Lies 1. Johannes 4 Vers 8',1,1),
('Was wünscht sich Salomo von Gott?','Frieden im Land','Gesundheit','Reichtum','Weisheit','Lies 1. Chronik 1, 10',4,1),
('Wer bat Gott um das Zeichen, dass die Wolle nass sein soll, aber der Boden drumherum trocken?','Gideon','Simson','Zacharias','Mose','Lies Richter 6,  36- 37',1,1),
('Wie nennt man die ersten vier Bücher im Neuen Testament?','Sie haben keinen speziellen Namen','Prophetenbücher','Evangelien','Weisheitsliteratur','Vergleiche im Inhaltsverzeichnis deiner Bibel. ',3,1),
('In welchem Ort wurde Jesus geboren?','In Nazareth','In Kapernaum','In Jerusalem','In Bethlehem','Lies Lukas 2 Vers 4 bis 7',4,1),
('Einmal heilt Jesus 10 Aussätzige auf einmal. Wie viele dankten ihm?','Keiner','Einer','Fünf','Alle ','Lies Lukas 17 Vers 11 bis 18',2,1),
('Zachhäus war …','… groß.','… dick.','… klein.','… sehr dünn.','Lies Lukas 19 Vers 3',3,1),
('Wie muss man an Jesus glauben, um in den Himmel zu kommen?','Wie ein Pfarrer!','Wie ein Erwachsener!','Wie ein Kind.','Wie ein Fischer!','Lies z.B. Lukas 18 Vers 17',3,1),
('Womit vergleicht Jesus sein Opfer am Kreuz?','Mit Brot und Wein.','Mit Gold und Silber.','Mit Rosen und Erde.','Mit Staub und Asche.','Lies z.B. Markus 14 Vers 22 bis 25',1,1),
('Welcher Jünger wollte Jesus mit dem Schwert verteidigen?','Simon Petrus','Thomas','Matthäus','Johannes','Lies Johannes 18 Vers 10',1,1),
('Die Eltern von Jesus hießen …','Maria und Petrus','Josef und Elisabeth','Josef und Maria','Zacharias und Elisabeth','Lies Lukas 2 Vers 4 und 5',3,1),
('Welche Aussage ist Teil des "Vater Unsers"?','Dein Reich komme.','Danke für deine Gnade.','Du bist der einzig wahre Gott.','Alles kommt von Dir.','Siehe Matthäus 6 Vers 9 bis 13',1,1),
('Welcher Jünger wollte Jesus nach seiner Auferstehung berühren?','Petrus','Johannes','Jakobus','Thomas','Lies Johannes 20 Vers 24 bis 25',4,1),
('Wann wurden Kinder nach der Geburt beschnitten?','Direkt nach der Geburt.','Nach acht Tagen.','Nach fünf Jahren.','Nach einem halben Jahr.','Lies z.B. Lukas 2 Vers 21',2,1),
('Wie oft wurde Jesus vom Teufel versucht?','Nie.','Siebenmal.','Dreimal.','Zweimal.','Siehe z.B. Matthäus 4 Vers 3 bis 11',3,1),
('Wer sorgt für genügend Licht im neuen Jerusalem?','Die Sonne, der Mond und die Sterne.','Gott und Jesus.','Ganz viele Glühwürmchen.','Eine riesiges Feuer.','Lies Offenbarung 21 Vers 23',2,1),
('Wer ist der Nachfolger von Mose?','Josua','Josef','König David','Petrus','Siehe z.B. 4. Mose 27 Vers 22 und 23',1,1),
('Wer war der erste König von Israel?','Saul','König David','Mose','Abraham','Lies 1. Samuel 10 Vers 19 bis 24',1,1),
('Wer wurde mit acht Jahren König?','David','Hiskia','Hoschea','Josia','Siehe 2. Könige 22 Vers 1',4,1),
('Welcher König war der Nachfolger von König David?','Jonathan','Salomo','Hiskia','Ahab','Lies 1. Könige 2 Vers 12',2,1),
('Wer kommt aus Bethlehem?','Rut','Petrus','David','Ester','Siehe z.B. 1. Samuel 17 Vers 58',3,1),
('Was passierte in dem Traum vom Pharao, den Josef deutete?','Sieben dünne Kühe fraßen sieben dicke Kühe.','Ägypten wurde von Feinden angegriffen.','Riesige Heuschrecken fraßen die Ernte der Ägypter auf.','Im Palast schwammen viele Meerestiere.','Lies 1. Mose 41 Vers 15 bis 25',1,1),
('Wer war der jüngste Sohn von Jakob?','Josef','Simeon','Juda','Benjamin','Lies z.B. 1. Mose 43 Vers 29',4,1),
('Was träumte Josef?','Er presste Trauben in den Becher des Pharaos.','Die Sonne, der Mond und elf Sterne verbeugten sich vor ihm.','Er hatte eine Familie mit 10 Kindern.','Er teilte das Wasser vom Meer.','Siehe 1. Mose 37 Vers 9',2,1),
('Wer wurde als Kind auf einem Fluss ausgesetzt?','Abinadab','Mose','Simson','Saul','Lies 2. Mose 2 Vers 3',2,1),
('Was passierte mit Mose, als er im Fluss gefunden wurde?','Er wurde an Ausländer verkauft.','Er wuchs  bei den wilden Tieren auf.','Die Tochter des Pharaos kümmerte sich um ihn.','Er wurde in seinem Korb im Fluss gelassen.','Lies 2. Mose 2 Vers 5 bis 10',3,1),
('Wie hießen die Söhne von Noah?','Josef, Dan und Naftali','Sem, Ham und Jafet','Mose und Aaron','Jakob und Esau','Lies z.B. 1. Mose 9 Vers 18',2,1),
('Wem begegnete Gott in einem brennenden Dornbusch?','Jesaja','Josua','Paulus','Mose','Siehe 2. Mose 3 Vers 2',4,1),
('Wer verkaufte sein Erstgeburtsrecht für ein Linsengericht?','Jakob','Esau','Absalom','Abel','Lies 1. Mose 25 Vers 29 bis 33',2,1),
('Wieso ging Petrus unter, nachdem er kurz auf dem Wasser gelaufen war?','Weil er auf die Wellen und den Wind schaute.','Weil er zu schwer war.','Weil er kein Loblied sang.','Weil seine Schuhe zu klein waren.','Lies Matthäus 14 Vers 30',1,1),
('Was will uns Gott durch Jesus schenken?','Ganz viel Geld.','Ein Leben, wo nur das passiert, was uns gefällt.','Viele Nachkommen.','Ewiges Leben.','Siehe z.B. Römer 5 Vers 21',4,1),
('Wen besuchte Maria, nachdem ein Engel ihr die Geburt von Jesus angekündigt hatte?','Jesaja','Petrus','Elisatbeth, die Frau von Zacharias','Abraham','Lies Lukas 1 Vers 39 und 40',3,1),
('Wie begegnete Gott Elia?','In einem stillen, sanften Sausen.','In einem brennenden Dornbusch.','In einem Erdbeben.','In einem Traum.','Siehe 1. Könige 19 Vers 12 und 13',1,1),
('Wie machte Jesus, als einige Eltern ihre Kinder zu ihm brachten?','Er schrie die Kinder an und schickte sie weg.','Er segnete die Kinder und nahm sie in den Arm.','Er ignorierte die Kinder.','Er lachte die Kinder aus.','Lies z.B. Markus 10 Vers 16',2,1),
('Welches Tier überredete Eva, von dem Baum der Erkenntnis zu essen?','Eine Eule','Eine Heuschrecke','Ein schwarzes Schaf','Eine Schlange','Lies 1. Mose 3 Vers 13',4,1),
('Wie hießen die ersten Menschen?','Abraham und Sara','Josef und Maria','Adam und Eva','Isaak und Rebekka','Lies z.B. 1. Mose 3 Vers 9 und 20',3,1),
('Warum trennten sich Abraham und Lot?','Es gab nicht genügend Weideplätze für alle Tiere.','Lot wollte in eine andere Gegend ziehen.','Damit die Einheimischen sie nicht angreifen würden.','Weil Abraham Lot nicht mehr mochte.','Lies 1. Mose 13 Vers 6',1,1),
('Was versprach Gott Abraham?','Viele Nachkommen','Weisheit','Dass Abraham König wird','Einen Palast','Siehe z.B. 1. Mose 13 Vers 16',1,1),
('Am wievielten Tag erschuf Gott die Vögel und die Wassertiere?','Am ersten Tag','Am dritten Tag','Am fünften Tag','Am sechsten Tag','Lies 1. Mose 1 Vers 20 bis 23',3,1),
('Wer war der erste Mensch, mit dem Gott einen Bund schloss?','David','Mose','Abraham','Noah','Lies 1. Mose 6 Vers 18',4,1),
('Welche Frau lachte, als ihr ein Sohn angekündigt wurde?','Maria','Elisabeth','Die Mutter von Simson','Sara','Siehe 1. Mose 18 Vers 10 bis 12',4,1),
('Wer war der Lieblingssohn von Isaak?','Jakob','Esau','Josef','Benjamin','Lies 1. Mose 25 Vers 28',2,1),
('Um den Erstgeburtssegen zu bekommen, gab Jakob sich als Esau aus. Wie machte er das?','Seine Mutter hatte das Fell von Ziegen um ihn gewickelt.','Er verstellte seine Stimme.','Er lief gebückt, sodass er kleiner war.','Er rieb sich mit Moos und Erde ein, um zu riechen sein Bruder.','Lies 1. Mose 27 Vers 15 und 16',1,1),
('Welchen Traum hatte Jakob, als er auf der Flucht vor Esau war?','Sieben dünne Kühe fraßen sieben dicke Kühe.','Ein Mann erschien ihm und bat Jakob, dass er zu ihnen kommt.','Auf einer Treppe stiegen Engel Gottes hinauf und hinab.','Er trug einen Korb mit Brot und Vögel fraßen ihn leer.','Siehe 1. Mose 28 Vers 12',3,1),
('Wem schenkte Jakob ein besonderes Gewand?','Seiner Frau Rahel','Seinem Sohn Josef.','Seinem Sohn Gad','Seinem Bruder Esau','Siehe 1. Mose 37 Vers 3',2,1),
('Was ließ Josef zusätzlich zum Getreide in die Säcke seiner Brüder stecken?','Das Geld für das Getreide.','Für jeden ein schönes Gewand.','Seine Krone.','Für jeden eine kleine Pyramidenfigur.','Lies z.B. 1. Mose 42 Vers 25',1,1),
('Wer ist kein Prophet?','Elia','Jesaja','Simson','Jona','Lies Richter 16 Vers 31',3,2),
('Wie viele Bücher hat das Alte Testament?','33','39','43','49','Vergleiche im Inhaltsverzeichnis deiner Bibel. ',2,2),
('Wie viele Bücher hat das Neue Testament?','22','25','27','30','Vergleiche im Inhaltsverzeichnis deiner Bibel. ',3,2),
('Wie viele Evangelien gibt es?','2','4','6','8','Vergleiche im Inhaltsverzeichnis deiner Bibel. ',2,2),
('Welchen Beruf hatte Lukas?','Arzt','Zimmermann','Fischer','Priester','Lies Kolosser 4 Vers 14',1,2),
('Welchen Beruf übte Matthäus aus, bevor er Jünger Jesu wurde?','Richter','Priester','Kaufmann','Zöllner','Lies Matthäus 9 Vers 9',4,2),
('Wie viele Weise Männer aus dem Morgenland besuchten Jesus?','2','3','4','Unbekannt','Lies Matthäus 1 Vers 1 bis 12',4,2),
('Welche Geschenke überbrachten die Weisen Männer aus dem Morgenland','Gold, Weihrauch, Myrre','Gold, Silber, Bronze','Gold, Getreide, Wein','Gold, Edelsteine, Schmuck','Lies Matthäus 1 Vers 11',1,2),
('Was war kein Geschenk der Weisen aus dem Morgenland','Gold','Diamanten','Weihrauch','Myrre','Lies Matthäus 1 Vers 11',2,2),
('Für welchen Lohn verriet Judas Iskariot Jesus?','Ein Kamel','10 Goldstücke','30 Silbermünzen','Unbekannt','Lies Matthäus 26 Vers 15',3,2),
('Wie viele Missionsreisen des Paulus werden in der Apostelgeschichte erwähnt?','1','2','3','4','Lies Apostelgeschichte 13 bis 21',3,2),
('Womit handelte Lydia?','Purpur','Schmuck','Getreide','Medizin','Lies Apostelgeschichte 16 Vers 14',1,2),
('Welche Strafe erlitten die Ägypter, weil sie das Volk Israel nicht ziehen ließen?','Pyramiden stürzten ein','Hungersnot','Trockenheit','10 Plagen','Lies 2. Mose 7 Vers 14 bis Kapitel 12 Vers 33',4,2),
('Wer wurde von einem Fisch verschluckt?','Noah','Joab','Jona','Josua','Lies Jona 2 Vers 1',3,2),
('Wie wurde Jericho erobert?','Schwertern und Lanzen','Katapulten','Feuer','Posaunen','Lies Josua 6 Vers 20',4,2),
('Vor den Toren welcher Stadt bekehrte sich Paulus?','Jerusalem','Jericho','Damaskus','Bethelehm','Lies Apostelgeschichte 3 Vers 3 bis 19',3,2),
('Wer erfuhr als erstes von der Geburt Jesu?','König Herodes','Der Hohepriester','Die Hirten','Die Weisen aus dem Morgenland','Lies Lukas 2 Vers 9 bis 14',3,2),
('Was bezeichnet man als den Sündenfall?','als Adam und Eva von der verbotenen Frucht aßen','Als David Ehebruch mit Batseba beging','Als Stephanus gesteinigt wurde','Als Jesus gekreuzigt wurde','',1,2),
('Gott ist allmächtig! Was kann er nicht?','Kranke heilen','Tode lebendig machen','Ewiges Leben schenken','Lügen','Lies 4. Mose 23 Vers 19',4,2),
('Wer war der erste König des vereinten Königreichs Israel?','Samuel','David','Saul','Josia','Lies 1. Samuel 8 Vers 4 und Kapitel 10 Vers 1',3,2),
('Welche Männer waren dicke Freunde?','Simson und Gideon','David und Saul','Jakob und Esau','David und Jonathan','Lies 1. Samuel 18 Vers 1 und 3',4,2),
('Was ist die Hauptstadt von Israel?','Jericho','Bethlehem','Jerusalem','Isra','Lies z.B. 2. Samuel 5 Vers 4 und 5',3,2),
('Wie lange regnete es bei der Sintflut?','Vierzehn Tage','Vierzehn Tage und Nächte','Vierzig Tage','Vierzig Tage und Nächte','Lies 1. Mose 7 Vers 12',4,2),
('In welcher Sprache wurde das Alte Testament verfasst?','Latein','Sanskrit','Hebräisch','Griechisch','',3,2),
('In welcher Sprache wurde das Neue Testament verfasst?','Griechisch','Römisch','Hebräisch','Latein','',1,2),
('Wer war Nebukadnezar?','Prophet Gottes','König von Babylon','Krieger der Philister','Einer der Weisen aus dem Morgenland','Lies z.B. 2. Könige 24 Vers 10',2,2),
('Wie speiste Jesus 5000 Menschen?','Mit Unmengen von Fladenbrot','Mit Obst und Gemüse von den umliegenden Feldern','Mit 5 Broten und 2 Fischen','Jeder hatte eine Brotzeit dabei','Lies z.B. Matthäus 14 Vers 19 bis 21',3,2),
('Jesus sagte ….','… ich bin Gott.','… ich bin der gute Hirte.','… ich bin der Stärkste.','… ich bin genial.','Lies Johannes 10 Vers 11',2,2),
('Was sagte Jesus nicht?','Ich bin das Brot','Ich bin die Tür','Ich bin das Salz.','Ich bin das Licht','Lies z.B. Matthäus 5 Vers 13',3,2),
('Was ist ein anderer Name für die 5 Bücher Moses?','Koran','Thora','Megiloth','Dekalog','',2,2),
('Beim Gleichnis vom vierfachen Ackerfeld werden die Körner auf dem Weg …','… gefressen','… zertreten','… vertrocknet','… schimmelig','Lies z.B. Matthäus 13 Vers 4',1,2),
('Wie bekommt man Ewiges Leben','Durch Beten und Bibellesen','Durch gute Taten tun','Durch den Glauben an Jesus','Jeder bekommt es einfach so','Lies z.B. Johannes 3 Vers 16',3,2),
('Welcher Pharisäer kam nachts zu Jesus um mit ihm zu reden?','Nikolaus','Nikodemus','Niklas','Nikolei','Lies Johannes 3 Vers 1 und 2',2,2),
('In welchem Buch der Bibel lesen wir die Schöpfungsgeschichte?','1. Buch Mose','4. Buch Mose','1. Buch Chronik','Prediger','Lies 1. Mose 1 Vers 1 bis Kapitel 2 Vers 4',1,2),
('Wen rettete Gott aus dem Gefängnis, musste dann aber vor verschlossener Tür warten?','Paulus','Silas','Johannes','Petrus','Lies Apostelgeschichte 12 Vers 6 bis 15',4,2),
('Wie starb Stephanus?','Kreuzigung','Steinigung','Hungertod','Unbekannt','Lies Apostelgeschichte 7 Vers 59 und 60',2,2),
('Wie heißt das erste Buch des Neuen Testaments?','Matthäus','Apostelgeschichte','1. Petrusbrief','1. Mose','Vergleiche im Inhaltsverzeichnis deiner Bibel. ',1,2),
('Wie heißt das letzte Buch des Neuen Testaments','Matthäus','Judasbrief','Hebräerbrief','Offenbarung','Vergleiche im Inhaltsverzeichnis deiner Bibel. ',4,2),
('Was macht Gott mit unserer Sünde, wenn wir um Vergebung bitten?','Er klagt uns an','Er verurteilt uns','Er bestraft uns','Er wirft sie in die Tiefen des Meeres','Lies Micha 7 Vers 19',4,2),
('Wer hörte als kleiner Junge nachts Gottes Stimme?','Noah','Abraham','Samuel','Amos','Lies 1. Samuel 3 Vers 1 und 4',3,2),
('Mit wie vielen Männern besiegte Gideon die Midianiter?','300','3000','13000','33000','Lies Richter 7 Vers 7',1,2),
('Weil Zacharias nicht glaubte im hohen Alter noch einen Sohn zu bekommen, wurde er …','Taub','Stumm','Blind','Gelähmt','Lies Lukas 1 Vers 13 bis 20',2,2),
('Jakob bekam von Gott einen anderen Namen! Welchen?','Jakobus','Jakob der Große','Israel','Juda','Lies 1. Mose 32 Vers 29',3,2),
('Was war die Stiftshütte?','Die Waffenkammer der Israeliten','Nomadenzelt der Urväter Abraham, Isaak, Jakob','Vorgänger des Tempels mit der Bundeslade','Der Ort wo israelitische Kinder Schreiben und Lesen lernten','Vergleiche  2. Mose 40 Vers 2 mit 1. Könige 6',3,2),
('Wer schützte die Kundschafter in der Stadt Jericho?','Eine fromme Familie','Henoch mit seinen Söhnen','Sara, die Frau Abrahams','Rahab, eine Prostituierte ','Lies Josua 2 Vers 2 bis 7',4,2),
('Wie viele Kundschafter kamen nach Jericho?','2','4','6','8','Lies Josua 2 Vers 1',1,2),
('Was bezeichnete Jesus als höchstes Gebot?','Du sollst keine anderen Götter haben','Heilige den Sabbat','Liebe Gott von ganzem Herzen','Du sollst nicht töten','Lies z.B. Matthäus 22 Vers 36 bis 38',3,2),
('Wofür steht das Schwert bei der geistlichen Waffenrüstung?','Für Gebet','Für die Predigt','Für das Tun von guten Taten','Für das Wort Gottes','Lies Epheser 6 Vers 17',4,2),
('Onesimus war …','… ein Tempeldiener','… ein römischer Soldat','… ein Sklave','… ein reicher Kornbauer','Lies Philemon Vers 10',3,2),
('Was ist die "sogenannte" Notrufnummer Gottes?','5015 (Aufgrund der Aussage von Psalm 50, 15)','0815 (umgangssprachlicher Ausdruck für "kein Problem")','110 (Notruf der Polizei)','7314 (Angelehnt an die Zahl von Wundern von denen die Bibel berichtet)','Lies Psalm 50 Vers 15',1,2),
('Wie heißt der Nachfolger als Apostel für Judas?','Barnabas','Sebulon','Matthias','Es gibt keinen.','Lies Apostelgeschichte 1 Vers 26',3,2),
('Wer war Set?','Ein Prophet','Ein Sohn von Adam und Eva','Ein König von Assyrien','Ein Jünger von Jesus','Lies 1. Mose 4 Vers 25',2,2),
('Was bedeutet der Name Ismael?','Gott hört','Der Starke','Geschenk','Gott vergisst mich nicht','Lies 1. Mose 16 Vers 11',1,2),
('Wie heißen die Freunde Hiobs?','Elifas, Bildad und Zofar','Elifas, Nehemia, Asaf','Petrus, Thomas, Johannes','Asaf, Jefunnes, Nun','Lies Hiob 2 Vers 11',1,2),
('Was soll in der Geschichte von Esther an dem Tag passieren, der von Haman ausgelost wurde?','Es wird verkündet, dass man die Schulden vom letzten Jahr nicht bezahlen muss','Eine große Feier zu Ehren des Königs','Eine Revolution gegen den König.','Die Vernichtung der Juden','Lies Esther 3 Vers 6 und 7',4,2),
('Was dachte der Priester Eli von Hanna?','Sie betet Gott an','Sie ist betrunken','Sie schläft','Sie will ihm ihre Waren verkaufen','Lies 1. Samuel 1 Vers 13',2,2),
('Womit vergleicht Jesus "das Himmelreich" nicht?','mit einem Schatz','mit einem vollen Fischnetz','mit einem Senfkorn','mit einer langen Leiter','Vergleiche Matthäus 13',4,2),
('Was ist richtig? ','Jesus sagt: Ich bin der gute Gott. ','Jesus sagt: ich bin der gute Hirte. ','Jesus sagt: Ich bin der stärkste Mensch auf Erden. ','Jesus sagt: Ich bin Beschützer aller Menschen.','Lies Johannes 10 Vers 11',2,2),
('Was hat Jesus nie gemacht? ','gesündigt','geweint','geschlafen','gehungert','Lies z.B. Hebräer 4 Vers 14 und 15',1,2),
('Was ist die Konsequenz von Sünde?','Krankheit','Pech','keine Konsequenz','Trennung von Gott','Vergleiche z.B. 1. Mose 3 Vers 23 und 24',4,2),
('An welchem Fluss kämpfte Jakob mit Gott?','Jabbok','Tigris','Jordan','Donau','1. Mose 32, 23 + 29',1,2),
('Wer wurde schon als Kind König?','Saul','Josia','David','Jehu','2. Könige 22, 1',2,2),
('Welchen Fehler machte König Hiskia?','Er ließ eine Götzenstatue aufrichten.','Er löste einen Gerichtsstreit ungerecht.','Er zeigt den Boten von Babylon seine Schatzkammern.','Er hatte viele heidnische Frauen.','Lies 2. Könige 20 Vers 13 und 17-19',3,2),
('Wie wollte Haman Mordechai töten?','Bei einem Raubüberfall.','Er stellte einen Galgen auf.','Er wollte ihn nicht töten.','Er wollte ihn den Löwen vorwerfen.','Lies Esther 5, 14',2,2),
('Welche Strafe erlitt Gehasi für seine Gier nach Reichtum?','Er bekam Aussatz.','Er konnte keine Kinder bekommen','Er musste jung sterben','Feinde kamen in das Land Israel.','Lies 2. Könige 6 Vers 26 bis 27',1,2),
('Was macht Michal, als sie sieht, dass David vor der Bundeslade hertanzt?','Sie versteckt sich.','Sie stellt sich schnell neben David und tanzt mit.','Sie sagt den Leuten, dass sie Palmwedel auf die Straße werfen sollen.','Sie verspottet David.','Lies 2. Samuel 6 Vers 16 und 20',4,2),
('Vor wem oder was musste David als König aus dem Palast fliehen?','Vor wilden Tieren.','Vor seinem Sohn.','Vor den Philistern.','Vor dem Volk, das einen Aufstand plante.','Lies 2. Samuel 15 Vers 13 und 16',2,2),
('In welchem Gleichnis werden alle Personen gleich behandelt?','Beim verlorenen Schaf','Bei den Arbeitern im Weinberg','Bei den zehn Brautjungfern','Beim verlorenen Sohn','Lies Matthäus 20 Vers 14',2,2),
('Welcher König lässt die Judäer aus dem Exil wieder in ihre Heimat zurückkehren?','Der babylonische König Og','Der babylonische König Nebukadnezar.','Der Perserkönig Kyrus','Der Perserkönig Xerxes','Lies Esra 1 Vers 1 bis 3',3,2),
('Woran erkennt das Volk Israel, dass der Gott von Elia und nicht Baal der Gott von König Ahab, der wahre Gott ist?','Der Gott von Elia lässt Feuer vom Himmel fallen.','Der Gott von Elia lässt das Volk in der Schlacht siegen.','Der Gott von Elia spricht hörbar zum Volk.','Der Gott von Elia lässt Elia leuchten.','Lies 1. Könige 18 Vers 23 und 24 ',1,2),
('Welche beiden Christen wurden nach einem Wunder fälschlicherweise als "Zeus" und "Hermes" verehrt?','Petrus und Johannes','Paulus und Silas','Jakobus und Petrus','Paulus und Barnabas','Lies Apostelgeschichte 14 Vers 11 und 12',4,2),
('Wer überlebte seine eigene Steinigung?','Paulus','Jesus','Petrus','Johannes','Lies Apostelgeschichte 14 Vers 19 und 20',1,2),
('Mit was vergleicht der Prophet Nathan David nach dessen Ehebruch?','Mit einem König','Mit einem Fischer','Mit einem reichen Mann','Mit einem Weinbauern','Lies 2. Samuel 12 Vers 4 und 7',3,2),
('Was sagt Hiob über sich?','Dass er durch die Unglücke für seine Schuld bestraft wird','Dass er unschuldig ist','Dass er der weiseste in seinem Land ist','Dass er ein Prophet ist','Lies Hiob 27 Vers 5',2,2),
('Die Israeliten siegten nicht bei Ai, weil Achan gesündigt hatte. Was hat er getan?','Er hat eine Götzenstatue angefertigt.','Er ist ohne Erlaubnis in das Heilige Zelt gegangen.','Er hat sich geweigert, mitzukämpfen.','Er hat Beute aus Jericho mitgenommen.','Lies Josua 7 Vers 20',4,2),
('Was hat Nabot, wofür ihn König Ahab beneidet?','Ein Weinberg','Ein kostbares Gewand','Viele Kinder','Eine schöne Frau','Lies 1. Könige 21 Vers 1 bis 2 und Vers 4',1,2),
('Wieso waren so viele Menschen am Teich Betesda?','Sie wollten Gottes Wort hören.','Sie hofften darauf, geheilt zu werden.','Sie arbeiteten dort.','Sie genossen die Natur.','Lies Johannes 5 Vers 2 bis 4',2,2),
('Jesus spricht … ','Ich bin der Beste und der Liebste.','Ich bin der Größte und der Stärkste.','Ich bin die Auferstehung und das Leben.','Ich denke, also bin ich.','Lies Johannes 11 Vers 25',3,2),
('Wer legt  Saulus die Hände auf, damit er wieder sehen konnte?','Nikodemus','Hananias','Lydia','Petrus','Lies Apostelgeschichte 9 Vers 17',2,2),
('Wie viele Tage blieb Jesus nach seiner Auferstehung noch bei seinen Jüngern?','3 Tage','12 Tage','40 Tage','120 Tage','Lies Apostelgeschichte 1 Vers 3',3,2),
('Von wie vielen Totenauferweckungen Jesu berichten die Evangelien?','Keiner','Einer','Drei','7','Siehe Lukas 8 Vers 53 und 54; Lukas 7 Vers 14 und 15 und Johannes 11 Vers 43 und 44 ',3,2),
('Welche Personen der Bibel waren keine Geschwister?','Petrus und Andreas','Esau und Jakob','Lea und Rahel','Abraham und Terach','Lies 1. Mose 11 Vers 31',4,2),
('Sara war …','Abrahams Frau und Halbschwester','Abrahams Frau und Cousine','Abrahams Frau und Nichte','Abrahams Frau und Stieftochter','Siehe 1. Mose 20 Vers 12.',1,2),
('Welchen Vogel lies Noah als erstes von der Arche fliegen?','Taube','Amsel','Rabe','Spatz','Siehe 1. Mose 8 Vers 7',3,2),
('Wer nahm verbotenerweise von der Beute aus Jericho?','Achan','Artos','Abram','Asaf','Siehe Josua 7 Vers 1',1,2),
('Wer war Absalom?','Ein Philister','Ein Sohn Davids','Ein Aussätziger','Ein Sohn Naomis.','Lies 2. Samuel 13 Vers 1',2,2),
('Wofür war Absalom bekannt?','Für seine Schönheit.','Für seine Kraft.','Für seine Güte.','Für seinen Reichtum.','Lies 2. Samuel 14 Vers 25',1,2),
('Das Buch Hohelied handelt …','.. vom Lob an Gott.','… von der Liebe.','… von der Größe des Königs.','… vom besten Musiker in Israel.','Siehe z.B. Hohelied 1 Vers 2',2,2),
('Psalm 23 handelt von Gott als … ','unserem Schöpfer.','unserem Hirten.','unserem König.','unserem Richter.','Siehe Psalm 23',2,2),
('Wer handelte in Philippi mit Purpur?','Ein Mann namens Lukas.','Eine Frau namens Mara.','Ein Mann namens Silas.','Eine Frau namens Lydia.','Lies Apostelgeschiche 16 Vers 14',4,2),
('In welches Land musste Jesus als Baby bzw. Kleinkind fliehen?','Ägypten','Syrien','Italien','Gar nicht.','Lies Matthäus 2 Vers 13 und 14',1,2),
('In welcher Stadt predigte Jona?','Jerusalem','Babylon','Ninive','Samaria','Lies Jona 3 Vers 3',3,2),
('Wer war ein Feind der Juden?','Melchisedek','Haman','Ahab','Abner','Lies Este 3 Vers 10',2,2),
('Wie hieß die Frau von König Ahab?','Elisabeth','Milka','Isebel','Johanna','Lies 1. Könige 16 Vers 31',3,2),
('Die Hirten schenkten Jesus zur Geburt …','2 Lämmer','Ein Schaffell','Wolle','Die Bibel erwähnt nichts davon.','Vergleiche Lukas 2 Vers 15 bis 17.',4,2),
('Wer verhinderte einen Mordanschlag auf König Xerxes?','Mordechai','Haman','Nehemia','Abraham','Lies Esther 2 Vers 21 bis 23',1,2),
('Welche Bedeutung hat es im Neuen Testament, wenn Christen beim Hinausgehen "den Staub von den Füßen schütteln"?','Es hat keine besondere Bedeutung.','Die Christen haben ihre Aufgabe erfolgreich abgeschlossen.','Die Christen überlassen Gott das Urteil über die Menschen dort, weil diese nicht an Jesus glauben wollten.','Es ist ein Erinnerungszeichen daran, dass Jesus den Jüngern die Füße gewaschen hat.','Lies Apostelgeschichte 13 Vers 51',3,2),
('Über welchen Berg zog Jesus nach Jerusalem ein? ','Den Berg Horeb','Den Ölberg','Den Tempelberg','Den Karmel','Siehe Markus 11 Vers 1',2,2),
('Wie hieß der blinde Bettler vor Jericho?','Barnabas','Barabas','Bartimäus','Barkeeper','Siehe Markus 10 Vers 46',3,2),
('Was hat Jesus nicht gesagt:','Die Ersten werden die Letzten sein.','Mein Joch ist sanft, und meine Last ist leicht.','Bittet so wird euch gegeben.','Lügen haben kurze Beine.','Siehe Matthäus 7 Vers 7; Matthäus 11 Vers 30; Matthäus 20 Vers 16',4,2),
('Wer war am Ostermorgen nicht am Grab von Jesus?','Salome','Maria aus Magdala','Johanna','Lydia','Lies Markus 16 Vers 1 bis 2; Lukas 24 Vers 1 und 10 und Johannes 20 Vers 1 bis 3',4,2),
('Wen erweckte Petrus durch Gottes Kraft von den Toten?','Tabita','Lazarus','Einen kleinen Jungen','Lydia','Siehe Apostelgeschichte 9 Vers 40',1,2),
('Wie viele Tage aß Jesus in der Wüste nichts?','12 Tage lang.','40 Tage lang.','30 Tage lang.','5 Tage lang.','Lies z.B. Matthäus 4 Vers 2',2,2),
('Wie heißt Nachfolger von Aaron?','David','Eli','Eleasar','Jehu','Lies z.B. 5. Mose 10 Vers 6',3,2),
('Wie geht der Vers weiter? "Nun, dann gebt dem Kaiser, was dem Kaiser gehört, ..."','"… und gebt den Menschen, was sie brauchen!"','"… und gebt Gott, was Gott gehört!"','"… und liebt eure Feinde!"','"… und zahlt die Tempelsteuer!"','Lies Lukas 20 Vers 25',2,2),
('Was steht in der Bibel über Engel?','Sie wissen genau, wann Jesus auf die Erde wiederkommt.','Sie können fliegen.','Sie erfüllen ihre Aufgaben immer in der Nacht.','Sie sind Gottes Diener.','Siehe z.B. Hebräer 1 Vers 7',4,2),
('Die Botschaft des Evangeliums ist nach der Bibel für Nicht-Christen … ?','Völliger Unsinn.','Ein Märchen','Ein interessante Philosophie.','Eine Erfindung.','Lies 1. Korinther 1 Vers 18',1,2),
('Wie viele Tore hat das neue Jerusalem?','12','4','24','7','Lies Offenbarung 21 Vers 12',1,2),
('Wer soll in einer Vision von Gott ein Buch essen, das süß wie Honig schmeckt?','Henoch und Melchisedek.','Daniel und Jesaja.','Johannes und Hesekiel.','Josua und Kaleb.','Siehe Hesekiel 3 Vers 3 und Offenbarung 10 Vers 9 bis 10',3,2),
('Bileam soll Israel verfluchen. Was macht er stattdessen?','Nichts.','Er segnet Israel dreimal.','Er schließt sich den Israeliten an.','Er zieht gegen die Israeliten in den Krieg.','Lies 4. Mose 24 Vers 10',2,2),
('Wer soll zuhören, wenn das Gesetz vorgelesen wird?','Nur die führenden Männer vom Volk Israel.','Alle Männer vom Volk Israel.','Alle Menschen (Männer, Frauen, Kinder) aus dem Volk Israel.','Alle Menschen aus dem Volk Israel und die Ausländer, die bei ihnen wohnen.','Siehe 5. Mose 31 Vers 12',4,2),
('Wen soll Elia zum König von Israel salben?','Jehu','Hasaël','David','Ahasja','Lies 1. Könige 19 Vers 16',1,2),
('Wer waren die ersten Könige vom geteilten Reich Israel und Juda?','Ahasja und Hiskia','Jerobeam und Hiskia','Jerobeam und Rehabeam','Ahab und Rehabeam','Siehe 1. Könige 12 Vers 20',3,2),
('Welches ist der längste Psalm in der Bibel?','Psalm 1','Psalm 150','Psalm 24','Psalm 119','Lies Psalm 119',4,2),
('Von wem stammt der Satz: "Es ist alles nichtig"?','Mose','Paulus','Jesus','Salomo','Siehe z.B. Prediger 12 Vers 8',4,2),
('Wer war nicht mit David verheiratet?','Michal','Rut','Abigajil','Batseba','Siehe Rut 1 Vers 4 und 4 Vers 13',2,2),
('Von wem wurde die Geburt nicht angekündigt?','Jesus','David','Johannes der Täufer','Josia','Lies 1. Könige 13 Vers 2 und  Lukas 1 Vers 13 und 31',2,2),
('Welcher König tat das, was Gott gefällt?','Joahas','Ahab','Josia','Hoschea','Lies 2. Könige 22 Vers 2',3,2),
('Wer ließ giftiges Essen genießbar werden?','Elisa','Jesus','Petrus','Josua','Lies 2. Könige 4 Vers 40 und 41',1,2),
('An wen wurde die Apostelgeschichte geschrieben?','An die führenden Männer der Juden','An Titus.','An die Gemeinde in Korinth.','An Theophilus.','Lies Apostelgeschichte 1 Vers 1',4,2),
('Wer war der älteste Sohn von Jakob?','Simeon','Ruben','Josef','Benjamin','Lies z.B. 1. Mose 36 Vers 23',2,2),
('Wie hieß die Frau von Mose?','Dina','Rahel','Zippora','Lydia','Siehe 2. Mose 2 Vers 21',3,2),
('Wie hießen die ersten beiden Söhne von Josef?','Ephraim und Manasse ','Jakob und Esau','Aaron und Mose','Josua und Kaleb','Siehe z.B. 1. Mose 48 Vers 8 und 9',1,2),
('Welche Person war nie auf der Flucht?','Jakob','David','Saul','Jesus','Lies z.B. 1. Mose 31 Vers 21; 2. Samuel 15 Vers 16 und Matthäus 2 Vers 13 und 14',3,2),
('Wie viele Jahre musste Jakob bei Laban arbeiten, bis er Rahel heiraten durfte?','1 Jahr','7 Jahre','10 Jahre','14 Jahre','Siehe 1. Mose 29 Vers 26 bis 30',2,2),
('Wie oft war Jakob auf der Flucht?','Nie.','Einmal.','Zweimal.','Dreimal.','Lies 1. Mose 27 Vers 42 und 43 und Kapitel 31 Vers 21',3,2),
('Was stahl Rahel ihrem Vater?','Seine Götterfiguren.','Ein Schmuckstück ihrer Mutter.','Ein Schaf.','Sein bestes Gewand.','Siehe 1. Mose 31 Vers 19',1,2),
('Was sagt die Bibel über Gott?','Gott verlässt einen Menschen nach 40 Jahren.','Gott ist nur der Gott der Israeliten.','Gott liebt nur arme Menschen.','Gott liebt allen Menschn auf der ganzen Welt. ','Johannes 3 Vers 16',4,2),
('Wer bekam erst nach langem Warten ein Kind?','Zippora','Sara','Rut','Maria','Lies z.B. Hebräer 11 Vers 11',2,2),
('Wer lief nicht weg?','Johannes der Täufer','Onesimus','Hagar','Jakob','Lies 1. Mose 16 Vers 6; 1. Mose 31 Vers 20 und 21 und Philemon Vers 17 und 18',1,2),
('Wer zog mit Abram nach Kanaan?','Laban','Josef','Lot','Nahor','Siehe 1. Mose 12 Vers 4 und 5',3,2),
('Was hielt Mose über das Meer, sodass es sich teilte?','Seinen Stab.','Seinen Mantel.','Einen Krug.','Einen Fisch.','Lies 1. Mose 14 Vers 16',1,2),
('Wie schlug Gideon mit seinen Männern die Midianiter in die Flucht?','Sie sangen ein Lied für Gott.','Sie zerbrachen Krüge und bliesen in die Posaunen.','Sie zündeten das Lager der Midianiter an.','Sie schickten einen Riesen zu den Midianitern.','Siehe Richter 7 Vers 19 bis 21',2,2),
('Mit wem zog Abraham nach Kanaan?','Mit seinen Söhnen.','Mit seinem Neffen Lot.','Mit seinem Bruder Nahor.','Unbekannt.','Lies 1. Mose 12 Vers 4',2,2),
('Wie viele Brüder hatte Josef?','Einen','Sieben','Elf','Zwölf','Lies z.B. 1. Mose 35 Vers 22b bis 26',3,2),
('Wie heißt der Engel, der Maria die Geburt von Jesus ankündigte?','Unbekannt','Michael','Abaddon','Gabriel','Lies Lukas 1 Vers 26 und 27',4,2),
('Was sagt die Bibel, wie Jesus wiederkommt?','So fröhlich wie ein Sänger.','So geheim wie ein Spion.','So unerwartet wie ein Dieb.','So prunkvoll wie ein Reicher.','Siehe z.B. 1. Thessalonicher 5 Vers 2',3,2),
('Was wollte Jesus den Menschen mit dem Gleichnis sagen, in dem eine Witwe immer wieder einen Richter bittet, dass er ihr hilft.','Gott will gerne den Menschen helfen, die ihn darum bitten.','Wir müssen mindestens 124 Mal für eine Sache beten, bevor Gott uns erhört.','Gott sind die Menschen egal.','Jeder Mensch ist ein Sünder.','Siehe Lukas 18 Vers 2 bis 8',1,2),
('Einmal heilte Jesus zehn Aussätzige. Wie viele von ihnen dankten ihm dafür?','Alle zehn.','Acht.','Zwei.','Einer.','Lies Lukas 17 Vers 17 und 18',4,2),
('Wie viele Jahre musste das Volk Israel durch die Wüste ziehen?','5 Jahre','20 Jahre','40 Jahre','50 Jahre','Lies z.B. 5. Mose 2 Vers 7',3,2),
('Wer begleitete Paulus auf seinen Reisen?','Johannes der Täufer','Silas','Petrus','Der Prophet Jesaja','Siehe z.B. Apostelgeschichte 15 Vers 40',2,2),
('Wer ist kein Nachkomme Davids?','König Hiskia','Jesus','Paulus','König Josia','Siehe Matthäus 1 Vers 6 bis 16',3,2),
('Wie hieß der Vater von Abraham?','Isaak','Nahor','Unbekannt','Terach','Lies 1. Mose 11 Vers 31',4,2),
('Warum lief die Sklavin Hagar davon?','Weil sie von Abrahams Frau Sara so schlecht behandelt wurde.','Weil sie vor Abraham Angst hatte.','Weil sie ein Schaf geklaut hatte.','Weil sie nach Ägypten wollte.','Lies 1. Mose 16 Vers 6',1,2),
('Von wem wurde die Geburt angekündigt?','Petrus','Simson','Paulus','Abraham','Siehe Richter 13 Vers 3 und 24',2,2),
('Abraham bat Gott darum, dass er Sodom nicht vernichtet, wenn wie viele Menschen dort an Gott glauben? ','100','50','10','5','Lies 1. Mose 18 Vers 32',3,2),
('Wen bat Josef darum, dem Pharao von ihm zu erzählen?','Den Gefängniswärter','Den Mundschenk vom Pharao','Den Leibwächter vom Pharao','Potifar','Siehe 1. Mose 40 Vers 9 bis 14',2,2),
('Welchen Posten gab der Pharao Josef?','Oberster Aufseher im Gefängnis','Oberster Aufseher der Leibwache','Stellvertreter des Pharao','Beamter über fünf Gebiete','Siehe z.B. 1. Mose 41 Vers 43',3,2),
('Wie lange dauerte die Hungersnot, als Josef in Ägypten war?','Sieben Jahre','Fünf Jahre','Drei Jahre','Ein Jahr','Lies z.B. 1. Mose 41 Vers 30 und 31',1,2),
('Wie reagierte Josef, als seine Brüder das erste Mal in Ägypten Getreide kaufen wollten?','Er schenkte ihnen ein Gebiet Ägyptens.','Er umarmte sie und feierte ein Wiedersehensfest. ','Er gab ihnen kein Getreide.','Er beschuldigte sie, dass sie Spione sind.','Lies 1. Mose 42 Vers 7 bis 9',3,2),
('Wessen Geburt wurde nicht angekündigt?','Moses','Isaaks','Samuels','Johannes der Täufer','Lies 1. Mose 18 Vers 10; 1.Samuel 1 Vers 17; Lukas 1 Vers 13',1,2),
('Wer ist keiner der Freunde Daniels?','Hananja','Hesekiel','Mischael','Asarja','Lies Daniel 2 Vers 16 und 17',2,3),
('Wer ist keiner der Jünger Jesu?','Petrus','Johannes','Markus','Matthäus','Lies z.B. Markus 3 Vers 16 bis 19',3,3),
('Wer ersetzte Judas Iskariot als Apostel?','Matthäus','Matthias','Manfred','Melchior','Lies Apostelgeschichte 1 Vers 26',2,3),
('Warum reiste der Kämmerer aus Äthiopien nach Jerusalem?','Um Gott anzubeten','Aus gesundheitlichen Gründen','Um Jesus zu sehen','Aus politischen Gründen','Lies Apostelgeschichte 8 Vers 27 und 28',1,3),
('Wie hieß der Sohn, den Abraham mit seiner Magd Hagar hatte?','Isaak','Ismael','Jakob','Esau','Lies 1. Mose 16 Vers 15',2,3),
('Wie hieß die Frau von Isaak?','Debora','Rahel','Sara','Rebekka','Lies 1. Mose 24 Vers 67',4,3),
('Wie alt wurde Mose','80','100','120','150','Lies 5. Mose 34 Vers 7',3,3),
('Wer wurde der Nachfolger Moses?','Josua','Jerobeam','Aaron','Abraham','Lies z.B. Josua 1 Vers 1 und 2',1,3),
('Wer erweckte laut Bibel niemanden zum Leben?','Elia','Elisa','Paulus','Johannes der Täufer','Lies 1. Könige 17 Vers 22; 2. Könige 4 Vers 32 bis 35 und Apostelgeschichte 20 Vers 10 und 12',4,3),
('Wer schrieb die Apostelgeschichte?','Paulus','Baruch','Lukas','Markus','Vergleiche Lukas 1 Vers 3 und Apostelgeschichte 1 Vers 1',3,3),
('Was wird auch als Dekalog bezeichnet?','Pfingstwunder','10 Gebote','Der Schöpfungsbericht','Sintflut','',2,3),
('Welches Tier der Bibel redete mit seinem Besitzer?','Hund','Kamel','Esel','Kuh','Lies 4. Mose 22 Vers 28 bis 30',3,3),
('Wer war die Urgroßmutter von König David?','Debora','Michal','Lea','Rut','Lies Rut 4 Vers 13 bis 17',4,3),
('Wer lies Eisen schwimmen?','Samuel','Jesus','Elisa','Noah','Siehe 2. Könige 6 Vers 6',3,3),
('Welches Wunder wird in jedem der vier Evangelien berichtet?','Speisung der 5000','Heilung des blinden Bartimäus','Jesus geht auf dem Wasser','Verwandlung von Wasser zu Wein','Siehe Matthäus 14 Vers 13 bis 21; Markus 6 Vers 31 bis 44; Lukas 9 Vers 10-17 und Johannes 6 Vers 1 bis 13',1,3),
('Welches war das erste Wunder Jesu?','Der Gang über das Wasser','Heilung des Gelähmten','Wasser zu Wein','Speisung der 5000','Lies Johannes 2 Vers 11',3,3),
('Welche Krankheit hatte Mephiboschet?','Er war blind','Er war taub','Er war gelähmt','Unbekannt','Lies 2. Samuel 4 Vers 4',3,3),
('Welches Tier dient uns zum Vorbild?','Ameise','Löwe','Adler','Esel','Siehe Sprüche 6 Vers 6',1,3),
('Was bedeutet „Messias“?','König','Retter','Gesalbter','Hohepriester','Lies Johannes 1 Vers 41',3,3),
(' Das Wort „Bibel“ kommt von dem griechischen Wort „biblios“. Was bedeutet es?','Anweisung','Buch','Geheimnis','Wunderworte','',2,3),
('Wie lange dauerte es die Stadtmauer von Jerusalem wieder aufzubauen?','52 Tage','100 Tage','Ein halbes Jahr','Fast zwei Jahre','Siehe Nehemia 6 Vers 15',1,3),
('Wer war Mordechai?','babylonischer Gelehrter','zum Tode verurteilter Verbrecher','assyrische Gottheit','Pflegevater von Königin Esther','Lies Ester 2 Vers 6 und 7',4,3),
('Welche beiden Kundschafter glaubten, dass mit Gottes Hilfe das Land eingenommen werden kann?','Mose und Aaron','Josua und Kaleb','Jakob und Josef','Melchisedek und Lot','Lies 4. Mose 14 Vers 7 und 8',2,3),
('Wie lang war die Arche?','~75 m','~100 m','~150 m','~200 m','Lies 1. Mose 6 Vers 15',3,3),
('Wer lebte in der Wüste und ernährte sich von Heuschrecken und Honig?','Elia','Abraham','Jesus','Johannes der Täufer','Lies z.B. Matthäus 3 Vers 4',4,3),
('Wer musste mit erhobenen Händen beten, um einen Kampf zu gewinnen?','Noah','Abraham','Mose','Josua','Lies 2. Mose 17 Vers 11 bis 13',3,3),
('In welcher Stadt wurden Nachfolger Jesus zum ersten Mal „Christen“ genannt?','Jerusalem','Antiochia','Rom','Ephesus','Lies Apostelgeschichte 11 Vers 26',2,3),
('Wer war der erste Nachfolger Jesu, der wegen seines Glaubens getötet wurde?','Jakobus','Johannes','Stephanus','Barnabas','Lies Apostelgeschichte 7  Vers 54 bis Kaptiel 8 Vers 3',3,3),
('Wie viele Brüder hatte David?','3','5','7','10','Lies 1. Samuel 16 Vers 10 und 11',3,3),
('Wie hieß der Vater von David','Isaak','Ismael','Isch-Boschet','Isai','Lies z.B. 1. Samuel 16 Vers 10 bis 12',4,3),
('Was bedeutet der Name Israel','Gott segnet','Gott ist da','Gotteskämpfer','Mit Gott geredet','Lies 1. Mose 32 Vers 29',3,3),
('Was ist kein Teil der geistlichen Waffenrüstung','Schild des Glaubens','Helm des Heils','Panzer der Gerechtigkeit','Speer der Wahrheit','Lies Epheser 6 Vers 14 bis 17',4,3),
('Das Wort Gottes ist schärfer als …','Ein zweischneidiges Schwert','Eine Rasierklinge','Ein Fallbeil','Eine Sichel','Lies Hebräer 4 Vers 12',1,3),
('Wer war Sanballat?','Ein griechischer Götze','Ein frommer Mann','Ein Berater von König Saul','Ein Feind von Nehemia','Lies z.B. Nehemia 4 Vers 1 und 2',4,3),
('Im Hause welches Mannes war Josef Aufseher?','Pilatus','Potifar','Porzius','Priska','Lies 1. Mose 39 Vers 1 bis 4',2,3),
('Wie heißt der Hohepriester, mit dem Jesus verglichen wird?','Aaron','Jesaja','Melchisedek','Zadok','Lies Hebräer 7 Vers 15',3,3),
('Wie heißt der Mann von Hanna?','Boas','Jefunnes','Elkana','Obed','Lies 1. Samuel 1 Vers 2',3,3),
('Wo lebte Hiob?','In Israel','In Ägypten','In Uz','In Moab','Lies Hiob 1 Vers 1',3,3),
('Wer bat Gott um das Zeichen, dass der Schatten der Sonnenuhr zurückwandert?','Gideon','Zacharias','Jesaja','König Hiskia','Lies 2. Könige 20 Vers 9 und 10',4,3),
('Welche Stämme Israels wollten östlich vom Jordan wohnen?','Ruben, Gad und der halbe Stamm Manasse','Benjamin, Naftali und der halbe Stamm Gad','Ephraim, Manasse und der halbe Stamm Juda','Issaschar, Asser und der halbe Stamm Dan','Lies 4. Mose 32 Vers 19 und 33',1,3),
('Mit wie vielen Kriegern besiegte Gideon die Midianiter?','300','3000','30000','unbekannt','Lies Richter 7 Vers 7',1,3),
('Wie viele Verse hat der kürzeste Psalm?','2','4','6','8','Siehe Psalm 117',1,3),
('Wie viele Verse hat der längste Psalem?','50','86','143','176','Siehe Psalm 119',4,3),
('Was war die kleinste Münze zur Zeit des Neuen Testaments?','Cent','Sesterze','Quadrantes','Lepton','Lies Markus 12 Vers 42',4,3),
('Welcher Prophet hat kein eigenes Buch in der Bibel?','Nahum','Nathan','Micha','Zefanja','Vergleiche im Inhaltsverzeichnis deiner Bibel.',2,3),
('Wofür ist Jael bekannt?','Für ihr festes Vertrauen in Gott.','Sie schrieb ein Danklied für Gott.','Sie tötete den Anführer der Feinde.','Für ihre Schönheit.','Lies Richter 4 Vers 21',3,3),
('Wer ist kein Richter?','Ehud','Asaf','Debora','Gideon','Siehe Richter 3 bis 6',2,3),
('An welche Gemeinde wird in der Offenbarung kein Brief geschrieben?','Ephesus','Philippi','Philadelphia','Sardes','Lies Offenbarung 2 Vers 1 bis Kapitel 3 Vers 14',2,3),
('Jesus spricht … ','Niemand kommt zum Vater denn durch mich. ','Alle dürfen bei Gott im Himmel sein.','Tut Gutes, dann kommt ihr zum Vater in den Himmel.','Betet fünf mal am Tag, dann kommt ihr in den Himmel.','Lies Johannes 14 Vers 6',1,3),
('Den Jünger Thomas nannte man auch …','… den Schlaumeier.','… den Weisen.','… den Zwilling.','… den Tollpatsch.','Lies z.B. Johannes 20 Vers 24',3,3),
('Welche Person der Bibel wird auch als "Freund Gottes" bezeichnet?','Noah','Abraham','Mose','Petrus','Lies Jakobusbrief 2 Vers 23',2,3),
('Psalm ist hebräisch und heißt:','Lob','Lied','Jubel','Gedicht','',2,3),
('Ester war Königin von welchem Reich?','Ägypten','Assyrien','Babylonien','Persien','Lies Ester 1 Vers 3 und 2 Vers 17',4,3),
('Samuel war …','Richter und Prophet','Richter und König','Prophet und Feldherr','Prophet und Viehzüchter','Lies 1. Samuel 7 Vers 15 und 1. Samuel 3 Vers 20',1,3),
('Welcher Prophet sagte, dass der Messias in Bethlehem geborgen werden wird?','Elia','Jeremia','Micha','Joel','Lies Micha 5 Vers 1',3,3),
('Wer bekommt seine Frau durch den Knecht seines Vaters?','Isaak','Jakob','Esau','Jonathan','Lies 1. Mose 24 Vers 51',1,3),
('Was erfüllte Jesus durch sein Sterben am Kreuz?','Gottes Anspruch auf Souveränität.','Gottes Anspruch auf Gerechtigkeit.','Gottes Anspruch auf Verherrlichung.','Gottes Anspruch auf Heiligung.','Lies 2. Korinther 5 Vers 21',2,3),
('Was sagt Gott nach Vollendung der Schöpfung?','Es ist vollbracht.','Super gemacht.','Oh wie schön ist diese Welt geworden.','Siehe, es war sehr gut.','1. Mose 1, 31',4,3),
('Was erschafft Gott am vierten Schöpfungstag?','Den Menschen.','Die Fische und Vögel.','Die Pflanzen.','Sonne, Mond und Sterne.','Lies 1. Mose 1 Vers 14 bis 19',4,3),
('Wer beaufsichtige die Steinigung des Stephanus? ','Niemand.','Der Hohepriester.','Herodes.','Saulus.','Lies Apostelgeschichte 7 Vers 58',4,3),
('Auf welchem Berg kam es zum "Gottesbeweis" zwischen Elia und den Baal-Priestern?','Berg Karmel.','Berg Zion.','Berg Horeb.','Berg Tabor.','Lies 1. Könige 18 Vers 20 bis 46',1,3),
('Mit welchen Waffen besiegte Gidieon die Midianiter?','Schwert und Schild.','Lanze und Schwert.','Pfeil und Bogen und Lanze','Fackel, Horn und  Tonkrug.','Lies Richter 7 Vers 16',4,3),
('Wie viel älter war Johannes der Täufer als Jesus?','6 Monate','12 Monate','6 Jahre','12 Jahre','Lies Lukas 1 Vers 36',1,3),
('Johannes der Täufer war ein …','Sadduzäer','Nasiräer','Pharisäer','Nazarener','Vergleiche 4. Mose 6 und Lukas 1 Vers 15',2,3),
('Wann wurde ein männlicher Junge normalerweise beschnitten?','Am Tag der Geburt.','Am 3. Tag nach der Geburt.','Am 8. Tag nach der Geburt.','Im 2. Monat nach der Geburt.','Lies Lukas 1 Vers 59 und Lk 2 Vers 21.',3,3),
('Der Mann von Elisabeth hieß …','Jakob','Gideon','Zacharias','Zebedäus','Lies Lukas 1 Vers 5 ',3,3),
('Von welchem Jünger sagt die Bibel, dass er verheiratet war?','Johannes','Petrus','Matthäus','Die Bibel gibt gar keine Angaben dazu.','Lies Matthäus 8 Vers 14',2,3),
('Für wie viel Geld wurde Josef nach Ägypten verkauft?','2 Goldtaler','20 Silberstücke','2 Drachmen und einen Esel','Einen Beutel voll Gold.','Lies 1. Mose 37 Vers 28',2,3),
('Für wie viel Geld wurde Jesus von Judas Iskariot verraten?','10 Goldmüzen','30 Silberlinge','Einen Beutel voll Gold.','unbekannt','Lies Matthäus 27 Vers 3',2,3),
('Was machte Jona als er im Bauch des Walfisches war?','Er schlief.','Er war ohnmächtig.','Er betete.','unbekannt.','Lies Jona 2 Vers 2',3,3),
('Wer sagte zu Gott: Hier bin ich, sende mich. ','Jesaja','Jeremia','Nehemia','Micha','Lies Jesaja 6 Vers 8',1,3),
('Wer war Joab?','Der Mann von Batseba.','Der Heerführer Davids.','Der König von Persien.','Der Prophet der zu David sprach.','Lies 2. Samuel 8 Vers 15',2,3),
('Salomo schrieb im Buch Prediger: ','Alles gehört mir.','Alles ist schlecht.','Alles hat seine Zeit.','Alles ist schön.','Lies Prediger 3 Vers 1',3,3),
('Wer vergaß die Tür zu öffnen, als Petrus nach seiner wunderbaren Befreiung klopfte?','Petrus','Maria Magdalena','Tamar','Rhode','Siehe Apostelgeschichte 12 Vers 13',4,3),
('Daniel konnte durch Gottes Hilfe …','Träume deuten','Tote lebendig machen','Kranke heilen.','Feuer vom Himmel fallen lassen.','Lies Daniel 2 Vers 47',1,3),
('Daniel nannte man auch … ','Jerubbaal','Beltschazar','Belsazar','Den Träumer','Siehe Daniel 1 Vers 7',2,3),
('Welcher Name kommt in der Bibel vor?','Milka','Sarotti','Nestle','Lind','Siehe z.B. 1. Mose 11 Vers 29',1,3),
('Wie lange war Saul König?','13 Jahre','27 Jahre','33 Jahre','40 Jahre','Siehe Apostelgeschichte 13 Vers 21',4,3),
('Wie lange war David König?','12 Jahre','20 Jahre','40 Jahre','55 Jahre','Siehe 2. Samuel 5 Vers 4',3,3),
('Wie lange war Salomo König?','7 Jahre','25 Jahre','40 Jahre','47 Jahre','Siehe 1. Könige 11 Vers 43',3,3),
('Wie lange dauerte es, bis der Tempel, den Salomo für Gott baute, fertig war?','2 Jahre','5 Jahre','7 Jahre','10 Jahre','Siehe 1. Könige 6 Vers 38',3,3),
('Wie lange dauerte es, bis die Paläste für Salomo fertig gebaut waren?','4 Jahre','8 Jahre','10 Jahre','13 Jahre','Siehe 1. Könige 7 Vers 1',4,3),
('Wo wohnte Samuel?','Rama','Margarine','Becel','Deli','Siehe 1. Samuel 7 Vers 17',1,3),
('Wie zahlreich waren die Israeliten, als sie nach Ägypten zogen, um dort zu leben?','70 Personen','700 Personen','7.000 Personen','70.000 Personen','Siehe 1. Mose 46 Vers 27',1,3),
('Was steht im letzten Satz der Bibel?','Ein Segenswunsch','Die Aufforderung, wachsam zu sein','Ein Gruß an die sieben Gemeinden in der Provinz Asia','Ein Ausblick in die Zukunft','Lies Offenbarung 22 Vers 21',1,3),
('Was bedeutet es, wenn jemand zur Zeit des Alten Testaments dem anderen seinen Schuh gab?','Es war ein Zeichen dafür, dass ein Sklave seinem Vorgesetzten gehorchen will.','Es war die Garantie dafür, dass ein Tausch oder eine Abmachung gilt.','Es war ein Erkennungsmerkmal für eine gute Freundschaft.','Diesen Brauch gab es nicht.','Siehe Rut 4 Vers 7  ',2,3),
('Welche Aussage über Demetrius ist falsch?','Demetrius verehrte die Göttin Diana.','Demetrius war Goldschmied.','Demetrius möchte nach einer Predigt von Paulus zu Jesus gehören.','Demetrius lebte in Ephesus.','Lies Apostelgeschichte 19 Vers 24 bis 28',3,3),
('Welches Verhalten wirft Paulus Petrus vor?','Dass Petrus Jesus verleugnet hat.','Dass Petrus den jüdischen Gesetzen wieder gehorcht, um den Juden zu gefallen.','Dass Petrus auch Nichtjuden von Jesus erzählt.','Dass Petrus zu wenige Missionsreisen unternimmt.','Lies Galater 2 Vers 11 bis 14',2,3),
('Bei welcher dieser Aussagen wird Jesus zitiert:','Geben ist seliger als nehmen.','Des Menschen Herz erdenkt sich seinen Weg, aber der HERR allein lenkt seinen Schritt.','Seid allezeit fröhlich, betet ohne Unterlaß, seid dankbar in allen Dingen.','Nun aber bleiben Glauben, Hoffnung, Liebe, diese drei; aber die Liebe ist die größte unter ihnen.','Siehe Apostelgeschichte 20 Vers 35',1,3),
('Was machten die ersten Christen?','Sie mieden Kontakt mit Nichtchristen.','Sie bauten Religionsschulen.','Sie stellten und malten überall Kreuze.','Sie teilten ihren Besitz.','Siehe Apostelgeschichte 2 Vers 45',4,3),
('Petrus und Johannes heilen den Gelähmten, der …','täglich vor dem "Nadelöhr Tor" saß.','täglich vor dem "Löwenmaul Tor" saß.','täglich vor dem "Schönen Tor" saß.','täglich vor dem "Ehren Tor" saß.','Lies Apostelgeschichte 3 Vers 2',3,3),
('Welche Bezeichnung  für Jesus ist richtig?','Fürst der Auferstehung','Fürst des Lebens','Fürst der Allmacht','Fürst der Vollendung','Lies Apostelgeschichte 3 Vers 15',2,3),
('Wer war römischer Kaiser in der Wirkungszeit von Jesus?','Julius Cäsar','Augustus','Tiberius','Nero','Lies Lukas 3 Vers 1',3,3),
('Wer war römischer Kaiser zur Zeit von Jesu Geburt?','Julius Cäsar','Augustus','Tiberius','unbekannt','Lies Lukas 2 Vers 1',2,3),
('Was will Gott uns durch Jesus wegnehmen und dafür geben?','Ein fleischernes Herz für ein steinernes Herz.','Ein Goldstück für ein Silberstück.','Weisheit für Dummheit','Bleibende Gesundheit für lange Krankheit.','Lies Hesekiel 36 Vers 26',1,3),
('Im Gebiet welchen Stammes lag die Stadt Jerusalem?','Simeon','Juda ','Ruben','Benjamin','2. Chronik 20 Vers 31',2,3),
('Wie reagierte die Königin von Saba auf die Weisheit und Macht Salomos?','Sie war neidisch.','Sie beschenkte Salomo reich.','Sie schmiedete Pläne gegen Salomo.','Sie protzte mit ihrer Weisheit und Macht.','Siehe 1. Könige 10 Vers 1 bis 13',2,3),
('Wie wurde Abimelech besiegt?','Durch eine Frau mit einem Mühlstein.','Durch einen Bauern mit seiner Hacke.','Durch ein Unwetter mit Blitz und Donner','Durch einen Pfeil eines Bogenschützen.','Lies Richter 9 Vers 53',1,3),
('Worüber haben sich die Jünger gestritten?','Wer auf dem Boot rudern musste.','Wer als erstes zu Essen bekommt.','Wer von Ihnen der Wichtigste ist.','Wer das Geld verwalten durfte.','Lies Lukas 22 Vers 24',3,3),
('Was soll Timotheus dem Paulus mitbringen?','Einen Mantel.','Neue Schuhe.','Seife.','Zu Essen.','Siehe 2. Timotheus 4 Vers 13',1,3),
('Was sagt Jesus nach seiner Auferstehung zu Petrus am See Tiberias?','Ich will dich zum Licht für die Völker machen.','Weide meine Schafe.','Sei ein lebendiger Fisch.','Du Kleingläubiger, warum hast du gezweifelt?','Lies Johannes 21 Vers 16',2,3),
('Welcher Prophet kündigt nicht die Zerstörung von Ninive an?','Zefanja','Nahum','Jona','Hesekiel','Siehe z.B. Zefanja 2 Vers 13; Nahum 1 Vers 1 und Jona 3 Vers 4',4,3),
('Welche beiden Personen ließen sich ein Stück Land nicht schenken, sondern wollten unbedingt dafür bezahlen?','David und Abraham.','Petrus und Jesus.','Josef und Josua.','Abraham und Boas.','Lies 1. Mose 23 Vers 8 bis 16 und 1. Chronik 21 Vers 22 bis 25',1,3),
('Was ist das Besondere an Henoch?','Gott nahm ihn zu sich, sodass er plötzlich nicht mehr da war. ','Er konnte kranke Menschen heilen.','Er war ein Prophet.','Durch seinen Plan besiegten die Israeliten die Feinde.','Lies z.B. Hebräer 11 Vers 5',1,3),
('Wer wird im Hebräerbrief als Vorbild des Glaubens genannt?','Der Prophet Elia.','Die Moabiterin Rut.','Abrahams Frau Sara.','Der Jünger Petrus.','Siehe Hebräer 11 Vers 11',3,3),
('Was steht in dem Sendschreiben an die Gemeinde in Sardes?','Sie ist eine tote Gemeinde.','Sie ist eine Ermutigung für andere Christen.','Es gibt viele Irrlehrer in dieser Gemeinde.','Es gibt viele Streitereien in dieser Gemeinde.','Lies Offenbarung 3 Vers 1',1,3),
('Was meint Paulus, wenn er den Christen in Korinth schreibt, dass er ihnen Milch gegeben hat?','Viele Christen waren krank und er hat sich um sie gekümmert.','Es ist eine verschlüsselte Botschaft dafür, dass er Timotheus zu ihnen geschickt hat.','Paulus hat ihnen als Spende für die Gemeinde eine Kuh dagelassen.','Paulus hat ihnen das Evangelium anfangs in ganz einfachen Worten erklärt. ','Siehe 1. Korinther 3 Vers 1 bis 3',4,3),
('An wen schreibt Johannes seinen dritten Brief?','An seinen Schüler Titus.','An seinen Freund Gajus.','An die Apostel.','An die Gemeinde in Rom.','Siehe 3. Johannesbrief Vers 1',2,3),
('Wer lehnte sich gegen König David auf?','Scheba','Jehu','Mefi-Boschet','Joab','Lies 2. Samuel 20 Vers 1 bis 2',1,3),
('Wie oft soll das Gesetz im Alten Testament vorgelesen werden?','Jede Woche.','Alle zwei Monate.','Alle sieben Jahre.','Jedes Jahr.','Lies 5. Mose 31 Vers 10 und 11',3,3),
('Wer war Hulda?','Eine der Frauen am Grab Jesu.','Die Frau von Josua.','Eine Prophetin.','Die Königin von Saba.','Lies z.B. 2. Chronik 34 Vers 22',3,3),
('Wer war der letzte König von Israel?','Hoschea','Ahab','Pekach','Salomo','Siehe 2. Könige 17 Vers 1 bis 4 und Vers 23',1,3),
('Wer war der letzte König von Juda?','Josia','Joahas','Jonathan','Zedekia','Lies z.B. 2. Chronik 36 Vers 11 und Vers 20 bis 21',4,3),
('In welchen Büchern der Bibel wird der Priester Melchisedek erwähnt?','Im Buch Josua, im Buch Jesaja und im Hebräerbrief','In 1. Mose, in den Psalmen und im Hebräerbrief.','In 1. Könige, in den Sprüchen und in der Apostelgeschichte','Im Matthäusevangelium, im Kolosserbrief und in der Offenbarung.','Lies 1. Mose 14 Vers 18 bis 20; Psalm 110 Vers 4 und Hebräer Kapitel 5 bis 7',2,3),
('Wer war der Sohn von Jefunnes?','Kaleb','Elia','Johannes der Täufer','Josia','Siehe 4. Mose 13 Vers 6',1,3),
('Wo fand der Knecht von Abraham Rebekka?','Im Vorhof des Tempels.','In der Wüste.','An einem Brunnen.','Auf dem Weg nach Jericho.','Lies 1. Mose 24 Vers 15 bis 17',3,3),
('Wer saß nie im Gefängnis?','Josef','Petrus','Paulus','Nehemia','Lies 1. Mose 39 Vers 19 und 20; Apostelgeschichte 12 Vers 3 und 4 und Kapitel 16 Vers 22 und 23',4,3),
('Was tat die Schriftrolle in der sechsten Vision Sacharjas?','Sie redete.','Sie flog.','Sie kämpfte mit den Feinden.','Sie glänzte in der Sonne.','Lies Sacharja 5 Vers 1',2,3),
('Wie hieß der Fluss, in dem Naaman siebenmal untertauchte, um gesund zu werden?','Euphrat','Nil','Jordan','Tigris','Siehe 2. Könige 5 Vers 14',3,3),
('Wer erlebte nicht, dass das Wasser sich teilte, sodass er ans andere Ufer gehen konnte?','Mose','Josua','Elisa','Petrus','Siehe 2. Mose 14 Vers 21 und 22; Josua 3 Vers 9 und Vers 14 bis 16 und 2. Könige 2 Vers 14',4,3),
('Wem versprach Gott, dass er noch so lange lebt, dass er den Messias sieht?','Simeon','Abraham','König David','Jesaja','Lies Lukas 2 Vers 25 bis 28',1,3),
('Wer baute nach dem Exil in Babylon als erstes den Tempel wieder auf?','Serubbabel','Paulus','Jesaja','Nehemia','Siehe z.B. Esra 5 Vers 2',1,3),
('Wem begegneten Maria und Josef im Tempel nach der Geburt Jesu?','Petrus und Jakobus','Der Prophetin Hanna und Simeon','Mose und Elia','Zacharias und Elisabeth mit Johannes dem Täufer','Siehe Lukas 2 Vers 24 bis 28 und Vers 36 bis 38',2,3),
('Wer kam, um Salomos Weisheit mit Rätseln zu prüfen?','Der persische König Xerxes','Petrus','Elia','Die Königin von Saba','Lies 1. Könige 10 Vers 1',4,3),
('Was ist möglich, sagt Jesus, wenn man einen Glauben hat, der so groß ist wie ein Senfkorn?','Man kann auf dem Wasser laufen.','Man kann alle Sprachen sprechen.','Man kann einen Berg verrücken.','Man kann fliegen.','Lies Matthäus 17 Vers 20',3,3),
('Wer schrieb für Jeremia die Botschaften Gottes auf? ','Baruch','Jojakim','Nahum','Petrus','Siehe Jeremia 36 Vers 4',1,3),
('Wie oft hielt der Diener von Elia auf dem Berg Karmel Ausschau nach Regen?','Einmal','Dreimal','Siebenmal','Zwölfmal','Lies 1. Könige 18 Vers 43 und 44',3,3),
('Von welchem Stamm sollten die Priestern für das Heiligtum kommen?','Vom  Stamm Benjamin.','Vom Stamm Ruben.','Vom Stamm Levi.','Vom Stamm Ephraim.','Lies z.B. 4. Mose 3 Vers 9 bis 10',3,3),
('In welche Reiche wurde das vereinte Königreich Israel nach Salomos Tod geteilt?','In Nordreich und Südreich.','In Ostreich und Westreich.','In Nordreich, Ostreich, Südreich und Westreich.','In Gebirgsreich und Flachland.','Lies z.B. 1. Könige 12 Vers 20',1,3),
('Was passierte Paulus als Christ nie?','Er saß nie im Gefängnis.','Er wurde nie als Gott verehrt.','Sein Haus wurde nie angezündet.','Er wurde nie gesteinigt.','Siehe Apostelgeschichte 14 Vers 11 bis 13; Apostelgeschichte 14 Vers 19 und Apostelgeschichte 16 Vers 22 und 23',3,3),
('Wo wohnte Paulus die ersten zwei Jahre seiner Gefangenschaft in Rom?','Bei einer Frau namens Lydia.','Bei seinem Freund Philemon.','Im Palastgefängnis.','In einer eigenen Wohnung.','Lies Apostelgeschichte 28 Vers 30',4,3),
('Von welcher Person legte man Kleidungsstücke auf Kranke, sodass sie gesund wurden?','Von Petrus.','Von Paulus.','Von Jesus.','Von Stephanus.','Lies Apostelgeschichte 19 Vers 12',2,3),
('Wie viele gebaute Tempel gibt es im neuen Jerusalem?','Keinen einzigen','7','700','Unendlich viele','Siehe Offenbarung 21 Vers 22',1,3),
('Was bedeutete das Zeichen, das Gott an Kain machte?','Kain ist ein Diener Gottes.','Kain ist der Stärkste.','Kain darf man nicht töten.','Kain soll der neue König sein.','Lies 1. Mose 4 Vers 15',3,3),
('Wer war ein Sohn von Adam und Eva?','Enosch','Set','Henoch','Jafet','Lies 1. Mose 4 Vers 25',2,3),
('Wem gab Abraham den zehnten Teil der Beute, als er Lot befreite?','Seiner Frau Sara','Dem König von Sodom','Seinem Neffen Lot','Dem Priester Melchisedek','Lies 1. Mose 14 Vers 20',4,3),
('Wem wollte Abraham seinen Besitz vererben, weil er dachte, dass er keine Kinder bekommt?','Seiner Sklavin Hagar','Seinem Knecht Eliëser','Seinem Bruder Nahor','Seinem Neffen Lot','Siehe 1. Mose 15 Vers 2 und 3',2,3),
('Woran wollte Abrahams Knecht die richtige Frau für Isaak erkennen?','Sie sollte freiwillig seine Kamele tränken.','Sie sollte drei verschiedene Sprachen sprechen.','Sie sollte die älteste Tochter sein.','Sie sollte die Tocher eines Propheten sein.','Lies 1. Mose 24 Vers 13 und 14',1,3),
('Wo wohnten die Israeliten in Ägypten?','Im Pharaonenpalast','In der Stadt Alexandria','In Goschen','Bei den Pyramiden von Gizeh','Siehe 1. Mose 47 Vers 5 und 6',3,3),
('Welcher Brief stammt nicht von Paulus?','Der Römerbrief','Der 1. Timotheusbrief','Der Kolosserbrief','Der Judasbrief','Lies Römer 1 Vers 1; 1.Timotheus 1 Vers 1 und Kolosser 1 Vers 1 und 2',4,3),
('Was passierte Paulus als Christ nie?','Er wurde nie ausgepeitscht.','Er wurde nie von einem Tier gebissen. ','Er erlitt nie Schiffbruch.','Er bekam nie Ärger von seiner Frau.','Siehe Apostelgeschichte 28 Vers 3; 2.Korinther 11 Vers 24 und 25 und 1.Korinther 7 Vers 7 (Paulus hatte keine Ehefrau)',4,3);