INSERT INTO questions (question, answer_1, answer_2, answer_3, answer_4, answer, difficulty) VALUES 
('Wann feiern wir den Geburtstag von Jesus?','Heiligabend','1.Weihnachtstag','2.Weihnachtstag','4.Advent',1,1),
('Wer war Jesus','Gottes Sohn','Musiker','Politiker','Sportler',1,1),
('Wie viele Jünger hatte Jesus','7','10','12','40',3,1),
('Wie hießen die Eltern von Jesus?','Zacharias und Elisabeth','Adam und Eva','Johannes und Maria','Josef und Maria',4,1),
('Wer führte das Volk Israel aus Ägypten?','David','Jakob','Esau','Mose',4,1),
('Wen bewahrte Gott vor den Löwen?','Daniel','Jona','Bileam','Paulus',1,1),
('Wie starb Jesus','Steinigung','Natürlicher Tod','Kreuzigung','Unbekannt',3,1),
('Wo wurde Jesus gekreuzigt?','Berg Golgatha','Tempelberg','Berg Karmel','Berg Sinai',1,1),
('Wie hoch war der Turm zu Babel?','85 m','135 m','150m','Unbekannt',4,1),
('Wie verhinderte Gott die Vollendung des Turmbaus in Babel?','Erdbeben','Krankheit','Sprachenentstehung','Unbekannt',3,1),
('Wann feiern wir die Auferstehung von Jesus','Ostern','Pfingsten','Himmelfahrt','Karfreitag',1,1),
('Was verkündete der Engel den Hirten bei der Geburt Jesu?','Gottes Strafe','Große Freude','Viele Nachkommen','Gar nichts',2,1),
('Was aßen die Israeliten in der Wüste?','Kokosnüsse','Manner','Manna','Brot',3,1),
('Was ist keins der 10 Gebote?','Nicht stehlen','Keine anderen Götter haben','Nicht töten','Nicht die Umwelt verschmutzen',4,1),
('Wer besiegte Goliat?','Daniel','Darius','David','Dagobert',3,1),
('Was ist keine der 10 Plagen?','Finsternis','Heuschrecken','Stechfliegen','Kopfschmerzen',4,1),
('Wer ist der älteste Mensch der Bibel?','Noah','Abraham','Methusalem','Unbekannt',3,1),
('In welche zwei Teile ist die Bibel unterteilt?','1.       Und 2. Kapitel','Altes und Neues Testament','Vorwort und Hauptteil','Berichte und Gedichte',2,1),
('Wovon handelt Psalm 23?','Vom Beten','Von Gott als Hirte','Von Sündenvergebung','Von Gott als dem Richter',2,1),
('In welchem Kindesalter redete Jesus mit den Schriftgelehrten? ','Mit 12 Jahren','Mit 14 Jahren','Mit 17 Jahren','unbekannt',1,1),
('Wann erschuf Gott den Menschen?','Am ersten Tag','Am dritten Tag','Am sechsten Tag','Am siebten Tag?',3,1),
('Was sind die ersten Worte der Bibel?','Es war einmal…','Am Anfang schuf Gott Himmel und Erde.','Aufgepasst, was jetzt kommt ist äußerst wichtig!','Liebe Leserin, lieber Leser …',2,1),
('Von welcher Frucht aßen Eva und Adam verbotener Weise?','Apfel','Orange','Mango','Unbekannt',4,1),
('Wie zog Jesus nach Jerusalem ein?','Er ritt auf einem Esel','Er wurde in einer Sänfte getragen','Er wanderte durch die Straßen','Als Sohn Gottes schwebte er hinein',1,1),
('Was machten die Jünger als Jesus im Garten Gethsemane betete?','Karten spielen','Wache halten','Schlafen','Mit beten',3,1),
('Was bewirkte der Heilige Geist beim ersten Pfingstfest?','Die Jünger bekamen starke Muskeln','Die Jünger konnten Menschen heilen','Die Jünger dichteten neue Lieder','Die Jünger sprachen in fremden Sprachen',4,1),
('Wer war der Bruder von Mose?','Anton','Aaron','Alfons','Ahab',2,1),
('Wie viele Menschen durften mit auf die Arche','2','4','6','8',4,1),
('Als Jesus am Kreuz starb, rief er …','Ihr seid alle schuldig','Es ist vollbracht','Ich habe Angst','Ich kann nicht mehr',2,1),
('Was machten Silas und Paulus um Mitternacht im Gefängnis','Sie lobten Gott','Sie randalierten','Sie planten einen Fluchtversuch','Sie riefen laut um Hilfe',1,1),
('Wer verleugnete dreimal Jesus zu kennen?','Johannes','Jakobus','Petrus','Andreas',3,1),
('Elia wurde am Bach Krit …','Von Freunden versorgt','Durch die Jagd versorgt','Von Raben versorgt','Mit Manna versorgt',3,1),
('Wie besiegte David den riesen Goliat?','Mit seinem Hirtenstab','Mit seiner Steinschleuder','Durch eine Falle','Durch einen Hinterhalt',2,1),
('Wer verlor seine Kraft durch das Schneiden der Haare?','Samuel','Simson','Saul','Absalom',2,1),
('Was war der Lieblingssohn von Jakob','Ruben','Juda','Josef','Gad',3,1),
('Wie viele Söhne hatte Jakob','6','8','10','12',4,1),
('Was sollte Abraham mit seinem Sohn Isaak machen?','Er sollte ihm Schafehüten beibringen','Er sollte ihm beibringen Kriege zu führen','Er sollte ihn nie alleine im Zelt lassen','Er sollte ihn opfern',4,1),
('Wer baute die Stadtmauer von Jerusalem wieder auf?','Jeremia','Nehemia','Serubbabel','Niemand',2,1),
('Wie viele Kundschafter begutachteten das verheißene Land?','6','12','25','40',2,1),
('Wie hießen die 3 Geschwister mit denen Jesus befreundet war?','Lazarus, Maria, Martha','Lamech, Lea, Rahel','Eli, Elisabeth, Hannah','Lukas, Lydia, Phoebe',1,1),
('Wie starb Abel?','Er erlitt einen Herzinfarkt','Er wurde von seinem Bruder erschlagen','Er ertrank im Jordan','Er starb im Krieg',2,1),
('Wer war die Mutter von Kain?','Rebekka','Maria','Eva','Unbekannt',3,1),
('Welcher König baute den Tempel?','Saul','David','Salomo','Hiskia',3,1),
('Wer war Machthaber in Jerusalem als Jesus verurteilt wurde?','Julius Cäsar','Pontius Pilatus','Pontius Felix','Pontius Augustus',2,1),
('Wer trug für Jesus das Kreuz?','Simon von Kyrene','Nikodemus','Gamaliel','Petrus',1,1),
('Jesus hatte Petrus vorhergesagt, dass er ihn dreimal verleugnet bevor …','… die Sonne aufgeht','… die Bauern auf ihre Felder gehen','… bevor die Glocken läuten','… bevor der Hahn kräht',4,1),
('Wer half in einem Gleichnis Jesu einem überfallenem Schwerverletzten?','Ein Priester','Ein Tempeldiener','Ein reicher Kaufmann','Ein Samariter',4,1),
('Wie verriet Judas Iskariot Jesus?','Durch einen Kuss','Durch eine Umarmung','Durch das Händeschütteln','Durch Schulterklopfen',1,1),
('Von wem wurde Jesus getauft?','Von Petrus','Von Gott selbst','Von Johannes dem Täufer','Jesus wurde nie getauft',3,1),
('Wer erfuhr als erstes von der Auferstehung Jesu?','Die engsten Jünger Jesu','Die Frauen am Grab','Die Emmausjünger','Alle Jünger gleichzeitig',2,1),
('Wer konnte anfangs nicht glauben, dass Jesus auferstanden sei?','Johannes','Jakobus','Pontius Pilatus','Thomas',4,1),
('Welchen Beruf hatte Nehemia?','Oberbefehlshaber der königlichen Leibwache','Zimmermann','Priester','Mundschenk des Königs',4,1),
('Wer kletterte auf einen Baum um Jesus zu sehen?','Zacharias','Zachäus','Zedekia','Melchisedek',2,1),
('Was tat Pontius Pilatus nachdem er Jesus verurteilt hatte?','Er kämmte seine Haare','Er winkte den jubelnden Menschen zu','Er wusch sich die Hände','Er schnäuzte sich die Nase',3,1),
('Was tat Jesus am Abend vor seiner Kreuzigung?','Er trank zu viel Wein','Er tanzte mit seinen Freunden','Er wusch seinen Jüngern die Füße','Er verteilte seinen Besitz unter seine Jünger',3,1),
('Was wird in einem Gleichnis neunundneunzigfach zurückgelassen?','Frauen und Kinder','Gold','Freunde','Schafe',4,1),
('Wo wächst Jesus auf?','Jerusalem','Bethlehem','Nazareth','Unbekannt',3,1),
('Wer war Jakobs Lieblingsfrau?','Lea','Rahel','Rebekka','Bila',2,1),
('Wie heißt ein ganz bekanntest Gleichnis von Jesus?','Der verlorene Sohn','Der verrückte Sohn','Der tote Sohn','Der egoistische Sohn',1,1),
('Jesus machte aus Fischern …','… Theologen','… Menschenfischer','… Adelige','… Soldaten',2,1);

INSERT INTO questions (question, answer_1, answer_2, answer_3, answer_4, answer, difficulty) VALUES 
('Wer ist kein Prophet?','Elia','Jesaja','Simson','Jona',3,2),
('Wie viele Bücher hat das Alte Testament?','33','39','43','49',2,2),
('Wie viele Bücher hat das Neue Testament?','22','25','27','30',3,2),
('Wie viele Evangelien gibt es?','2','4','6','8',2,2),
('Welchen Beruf hatte Lukas?','Arzt','Zimmermann','Fischer','Priester',1,2),
('Welchen Beruf übte Matthäus aus, bevor er Jünger Jesu wurde?','Richter','Priester','Kaufmann','Zöllner',4,2),
('Wie viele Weise Männer aus dem Morgenland besuchten Jesus?','2','3','4','Unbekannt',4,2),
('Welche Geschenke überbrachten die Weisen Männer aus dem Morgenland','Gold, Weihrauch, Myrre','Gold, Silber, Bronze','Gold, Getreide, Wein','Gold, Edelsteine, Schmuck',1,2),
('Was war kein Geschenk der Weisen aus dem Morgenland','Gold','Diamanten','Weihrauch','Myrre',2,2),
('Für welchen Lohn verriet Judas Iskariot Jesus?','Ein Kamel','10 Goldstücke','30 Silbermünzen','Unbekannt',3,2),
('Wie viele Missionsreisen des Paulus werden in der Apostelgeschichte erwähnt?','1','2','3','4',3,2),
('Womit handelte Lydia?','Purpur','Schmuck','Getreide','Medizin',1,2),
('Welche Strafe erlitten die Ägypter, weil sie das Volk Israel nicht ziehen ließen?','Pyramiden stürzten ein','Hungersnot','Trockenheit','10 Plagen',4,2),
('Wer wurde von einem Fisch verschluckt?','Noah','Joab','Jona','Josua',3,2),
('Wie wurde Jericho erobert?','Schwertern und Lanzen','Katapulten','Feuer','Posaunen',4,2),
('Vor den Toren welcher Stadt bekehrte sich Paulus?','Jerusalem','Jericho','Damaskus','Bethelehm',3,2),
('Wer erfuhr als erstes von der Geburt Jesu?','König Herodes','Der Hohepriester','Die Hirten','Die Weisen aus dem Morgenland',3,2),
('Was bezeichnet man als den Sündenfall?','als Adam und Eva von der verbotenen Frucht aßen','Als David Ehebruch mit Batseba beging','Als Stephanus gesteinigt wurde','Als Jesus gekreuzigt wurde',1,2),
('Gott ist allmächtig! Was kann er nicht?','Kranke heilen','Tode lebendig machen','Ewiges Leben schenken','Lügen',4,2),
('Wer war der erste König des vereinten Königreichs Israel?','Samuel','David','Saul','Josia',3,2),
('Welche Männer waren dicke Freunde?','Simson und Gideon','David und Saul','Jakob und Esau','David und Jonathan',4,2),
('Was ist die Hauptstadt von Israel?','Jericho','Bethlehem','Jerusalem','Isra',3,2),
('Wie lange regnete es bei der Sintflut?','Vierzehn Tage','Vierzehn Tage und Nächte','Vierzig Tage','Vierzig Tage und Nächte',4,2),
('In welcher Sprache wurde das Alte Testament verfasst?','Latein','Sanskrit','Hebräisch','Griechisch',3,2),
('In welcher Sprache wurde das Neue Testament verfasst?','Griechisch','Römisch','Hebräisch','Latein',1,2),
('Wer war Nebukadnezar?','Prophet Gottes','König von Babylon','Krieger der Philister','Einer der Weisen aus dem Morgenland',2,2),
('Wie speiste Jesus 5000 Menschen?','Mit Unmengen von Fladenbrot','Mit Obst und Gemüse von den umliegenden Feldern','Mit 5 Broten und 2 Fischen','Jeder hatte eine Brotzeit dabei',3,2),
('Jesus sagte ….','… ich bin Gott.','… ich bin der gute Hirte.','… ich bin der Stärkste.','… ich bin genial.',2,2),
('Was sagte Jesus nicht?','Ich bin das Brot','Ich bin die Tür','Ich bin das Salz.','Ich bin das Licht',3,2),
('Was ist ein anderer Name für die 5 Bücher Moses?','Koran','Thora','Megiloth','Dekalog',2,2),
('Beim Gleichnis vom vierfachen Ackerfeld werden die Körner auf dem Weg …','… gefressen','… zertreten','… vertrocknet','… schimmelig',1,2),
('Wie bekommt man Ewiges Leben','Durch Beten und Bibellesen','Durch gute Taten tun','Durch den Glauben an Jesus','Jeder bekommt es einfach so',3,2),
('Welcher Pharisäer kam nachts zu Jesus um mit ihm zu reden?','Nikolaus','Nikodemus','Niklas','Nikolei',2,2),
('In welchem Buch der Bibel lesen wir die Schöpfungsgeschichte?','1. Buch Mose','4. Buch Mose','1. Buch Chronik','Prediger',1,2),
('Wen rettete Gott aus dem Gefängnis, musste dann aber vor verschlossener Tür warten?','Paulus','Silas','Johannes','Petrus',4,2),
('Wie starb Stephanus?','Kreuzigung','Steinigung','Hungertod','Unbekannt',2,2),
('Wie heißt das erste Buch des Neuen Testaments?','Matthäus','Apostelgeschichte','1. Petrusbrief','1. Mose',1,2),
('Wie heißt das letzte Buch des Neuen Testaments','Matthäus','Judasbrief','Hebräerbrief','Offenbarung',4,2),
('Was macht Gott mit unserer Sünde, wenn wir um Vergebung bitten?','Er klagt uns an','Er verurteilt uns','Er bestraft uns','Er wirft sie in die Tiefen des Meeres',4,2),
('Wer hörte als kleiner Junge nachts Gottes Stimme?','Noah','Abraham','Samuel','Amos',3,2),
('Mit wie vielen Männern besiegte Gideon die Midianiter?','300','3000','13000','33000',1,2),
('Weil Zacharias nicht glaubte im hohen Alter noch einen Sohn zu bekommen, wurde er …','Taub','Stumm','Blind','Gelähmt',2,2),
('Jakob bekam von Gott einen anderen Namen! Welchen?','Jakobus','Jakob der Große','Israel','Juda',3,2),
('Was war die Stiftshütte?','Die Waffenkammer der Israeliten','Nomadenzelt der Urväter Abraham, Isaak, Jakob','Vorgänger des Tempels mit der Bundeslade','Der Ort wo israelitische Kinder Schreiben und Lesen lernten',3,2),
('Wer schützte die Kundschafter in der Stadt Jericho?','Eine fromme Familie','Henoch mit seinen Söhnen','Sara, die Frau Abrahams','Rahab, eine Prostituierte ',4,2),
('Wie viele Kundschafter kamen nach Jericho?','2','4','6','8',1,2),
('Was bezeichnete Jesus als höchstes Gebot?','Du sollst keine anderen Götter haben','Heilige den Sabbat','Liebe Gott von ganzem Herzen','Du sollst nicht töten',3,2),
('Wofür steht das Schwert bei der geistlichen Waffenrüstung?','Für Gebet','Für die Predigt','Für das Tun von guten Taten','Für das Wort Gottes',4,2),
('Onesimus war …','… ein Tempeldiener','… ein römischer Soldat','… ein Sklave','… ein reicher Kornbauer',3,2);

INSERT INTO questions (question, answer_1, answer_2, answer_3, answer_4, answer, difficulty) VALUES 
('Wer ist keiner der Freunde Daniels?','Hananja','Hesekiel','Mischael','Asarja',2,3),
('Wer ist keiner der Jünger Jesu?','Petrus','Johannes','Markus','Matthäus',3,3),
('Wer ersetzte Judas Iskariot als Apostel?','Matthäus','Matthias','Manfred','Melchior',2,3),
('Warum reiste der Kämmerer aus Äthiopien nach Jerusalem?','Um Gott anzubeten','Aus gesundheitlichen Gründen','Um Jesus zu sehen','Aus politischen Gründen',1,3),
('Wie hieß der Sohn, den Abraham mit seiner Magd Hagar hatte?','Isaak','Ismael','Jakob','Esau',2,3),
('Wie hieß die Frau von Isaak?','Debora','Rahel','Sara','Rebekka',4,3),
('Wie alt wurde Mose','80','100','120','150',3,3),
('Wer wurde der Nachfolger Moses?','Josua','Jerobeam','Aaron','Abraham',1,3),
('Wer erweckte laut Bibel niemanden zum Leben?','Elia','Elisa','Paulus','Petrus',4,3),
('Wer schrieb die Apostelgeschichte?','Paulus','Baruch','Lukas','Markus',3,3),
('Was wird auch als Dekalog bezeichnet?','Pfingstwunder','10 Gebote','Der Schöpfungsbericht','Sintflut',2,3),
('Welches Tier der Bibel redete mit seinem Besitzer?','Hund','Kamel','Esel','Kuh',3,3),
('Wer war die Urgroßmutter von König David?','Debora','Michal','Lea','Rut',4,3),
('Wer lies Eisen schwimmen?','Samuel','Jesus','Elisa','Noah',3,3),
('Welches Wunder wird in jedem der vier Evangelien berichtet?','Speisung der 5000','Heilung des blinden Bartimäus','Jesus geht auf dem Wasser','Verwandlunga von Wasser zu Wein',1,3),
('Welches war das erste Wunder Jesu?','Der Gang über das Wasser','Heilung des Gelähmten','Wasser zu Wein','Speisung der 5000',3,3),
('Welche Krankheit hatte Mephiboschet?','Er war blind','Er war taub','Er war gelähmt','Unbekannt',3,3),
('Welches Tier dient uns zum Vorbild?','Ameise','Löwe','Adler','Esel',1,3),
('Was bedeutet „Messias“?','König','Retter','Gesalbter','Hohepriester',3,3),
(' Das Wort „Bibel“ kommt von dem griechischen Wort „biblios“. Was bedeutet es?','Anweisung','Buch','Geheimnis','Wunderworte',2,3),
('Wie lange dauerte es die Stadtmauer von Jerusalem wieder aufzubauen?','52 Tage','100 Tage','Ein halbes Jahr','Fast zwei Jahre',1,3),
('Wer war Mordechai?','babylonischer Gelehrter','zum Tode verurteilter Verbrecher','assyrische Gottheit','Pflegevater von Königin Esther',4,3),
('Welche beiden Kundschafter glaubten, dass mit Gottes Hilfe das Land eingenommen werden kann?','Mose und Aaron','Josua und Kaleb','Jakob und Josef','Melchisedek und Lot',2,3),
('Wie lang war die Arche?','~75 m','~100 m','~150 m','~200 m',3,3),
('Wer lebte in der Wüste und ernährte sich von Heuschrecken und Honig?','Elia','Abraham','Jesus','Johannes der Täufer',4,3),
('Wer musste mit erhobenen Händen beten, um einen Kampf zu gewinnen?','Noah','Abraham','Mose','Josua',3,3),
('In welcher Stadt wurden Nachfolger Jesus zum ersten Mal „Christen“ genannt?','Jerusalem','Antiochia','Rom','Ephesus',2,3),
('Wer war der erste Nachfolger Jesu, der wegen seines Glaubens getötet wurde?','Jakobus','Johannes','Stephanus','Barnabas',3,3),
('Wie viele Brüder hatte David?','3','5','7','10',3,3),
('Wie hieß der Vater von David','Isaak','Ismael','Isch-Boschet','Isai',4,3),
('Was bedeutet der Name Israel','Gott segnet','Gott ist da','Gotteskämpfer','Mit Gott geredet',3,3),
('Was ist kein Teil der geistlichen Waffenrüstung','Schild des Glaubens','Helm des Heils','Panzer der Gerechtigkeit','Speer der Wahrheit',4,3),
('Das Wort Gottes ist schärfer als …','Ein zweischneidiges Schwert','Eine Rasierklinge','Ein Fallbeil','Eine Sichel',1,3),
('Wer war Sanballat?','Ein griechischer Götze','Ein frommer Mann','Ein Berater von König Saul','Ein Feind von Nehemia',4,3),
('Im Hause welches Mannes war Josef Aufseher?','Pilatus','Potifar','Porzius','Priska',2,3);